nextcloud/talk-android

app/src/GPlay/java/com/nextcloud/talk/services/firebase/MagicFirebaseInstanceIDService.java
app/src/GPlay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.java
app/src/GPlay/java/com/nextcloud/talk/utils/ClosedInterfaceImpl.java
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/adapters/items/NewCallHeaderItem.java
app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.java
app/src/main/java/com/nextcloud/talk/controllers/CallsListController.java
app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.java
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.java
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
app/src/main/java/com/nextcloud/talk/interfaces/ClosedInterface.java
app/src/main/java/com/nextcloud/talk/jobs/creator/MagicJobCreator.java
app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.java
app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
app/src/main/java/com/nextcloud/talk/utils/ShareUtils.java
app/src/main/java/com/nextcloud/talk/utils/database/user/UserUtils.java
app/src/main/java/com/nextcloud/talk/utils/ssl/SSLSocketFactoryCompat.kt
app/src/main/java/com/nextcloud/talk/webrtc/MagicAudioManager.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicProximitySensor.java
app/src/test/java/com/nextcloud/talk/ExampleUnitTest.java

as discussed on IRC fixing codacy warnings

Improving codacy score

---

app/src/main/java/com/nextcloud/talk/adapters/items/AppItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/MenuItem.java
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
app/src/main/res/layout/rv_item_app.xml
app/src/main/res/layout/rv_item_menu.xml
app/src/main/res/values/colors.xml

Fix #151 recoloring bottom menu, slightly smaller text size

Optimize bottom sheet menu

---

app/src/main/res/layout/rv_item_app.xml
app/src/main/res/layout/rv_item_menu.xml

now the items have a white background. For whatever reason setting the background color on any parent element doesn't work...

Fix bottom sheet background color

---

docs/TURN.md

- Port from help.nextcloud.com as requested: https://help.nextcloud.com/t/howto-setup-nextcloud-talk-with-turn-server/30794/2?u=michaing
- Signed-off-by: Micha Felle <micha.felle@gmx.net>
- Hope it's okay to stay a bid anonym here 🙂.

Add TURN server documentation

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/CallItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/res/layout/controller_call_notification.xml
app/src/main/res/values-ko/strings.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

with 
* dark theme and 
* constraint layout
Beware that the system bar will still be blue. In order to get that part in black one would need to set another theme like `NoActionBar`

revamp call notification screen 

---

app/src/main/java/com/nextcloud/talk/adapters/items/MenuItem.java
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
app/src/main/res/values/strings.xml

Defining more specific bottom sheet header strings

---

app/src/main/java/com/nextcloud/talk/controllers/CallController.java

see https://stackoverflow.com/questions/44334233/why-is-the-stringbuilder-chaining-pattern-sb-appendx-appendy-faster-than-reg/44338950

improve performance

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.java

Signed-off-by: Mario Danic <mario@lovelyhq.com>

Fix push for 3.1 when out of app

---

app/src/main/res/values/strings.xml

Reported at Transifex.
See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/130098100?q=issue%3Aopen
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>

Changed wording for authentication

---

app/src/main/java/com/nextcloud/talk/activities/BaseActivity.java
app/src/main/java/com/nextcloud/talk/controllers/CallController.java
app/src/main/java/com/nextcloud/talk/events/MediaStreamEvent.java
app/src/main/java/com/nextcloud/talk/events/PeerConnectionEvent.java
app/src/main/java/com/nextcloud/talk/events/SessionDescriptionSendEvent.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicAudioManager.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebRTCUtils.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java

Signed-off-by: Mario Danic <mario@lovelyhq.com>

Add screensharing support

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/res/values/strings.xml

Signed-off-by: Mario Danic <mario@lovelyhq.com>

First steps towards fixing german

---

app/src/main/res/values-ca/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/styles.xml

Signed-off-by: Amanda Rosene <arosene83@gmail.com>

Fix #498 Top right menu in conversation is blue

---

app/build.gradle

Included fix for counterTextColor conflict with material library.
Signed-off-by: Daniel Bailey <daniel.bailey@grappleIT.co.uk>

Increment TextFieldBoxes to 1.4.5.

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.java
app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java

As requested in https://github.com/nextcloud/android/pull/4286

FIDO U2F Support

---

README.md

fix  #688
Signed-off-by: Marco Ambrosini <marcoambrosini@pm.me>

Remove dead contributing guidelines link from the readme

---

app/src/main/java/com/nextcloud/talk/utils/ssl/MagicKeyManager.java

I was able to reproduce and fix (at least for me) the problem described in #195 
Signed-off-by: Stephan Ritscher <no3pam@gmail.com>

Fix NullPointerException on (first) account creation with client certificates (#195)

---

app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
app/src/main/java/com/nextcloud/talk/newarch/domain/repository/offline/ConversationsRepository.kt
app/src/main/java/com/nextcloud/talk/newarch/features/account/loginentry/LoginEntryView.kt
app/src/main/java/com/nextcloud/talk/newarch/features/contactsflow/contacts/ContactsViewModel.kt
app/src/main/java/com/nextcloud/talk/newarch/features/contactsflow/groupconversation/GroupConversationViewModel.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/ConversationListViewModelFactory.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/ConversationPresenter.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/ConversationsListSource.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/ConversationsListView.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/ConversationsListViewModel.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/ConversationsListViewNetworkState.kt
app/src/main/java/com/nextcloud/talk/newarch/features/conversationsList/di/module/ConversationsListModule.kt
app/src/main/res/layout/conversations_list_view.xml

Minor code cleanup with Kotlin practices.
Signed-off-by: Marijan Šikić <marijansikic77@gmail.com>

minor code cleanup

---

app/src/main/res/values/strings.xml

Correction of the word: "sent" to "send".

Correction of the description

---

README.md

Used the screens from the `fastlane` folder like @giulianograssi suggested in #239
@mario you probably should update the screenshots in the Play Store as well - they look different from what i can see (at least in the F-Droid version) :wink:.

Add screenshots to README.md

---

app/src/main/res/values-night/colors.xml

text color change for dark mode

---

README.md

It's good to have an f-droid badge

F-droid badge

---

app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt

Prevent crash from koin logger after kotlin update

---

app/build.gradle

Bump to 8.0.10

---

app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatPresenter.kt
app/src/main/res/layout/item_message_quote.xml
app/src/main/res/layout/rv_chat_item.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml

Closes #834.
| Before | After | 
| --------- | ------ |
| ![screenshot-2020-09-25_18 13 54 403](https://user-images.githubusercontent.com/1926270/94296917-8b284380-ff5b-11ea-95ee-f58a3fbc39d0.png)  ![screenshot-2020-09-25_18 14 13 259](https://user-images.githubusercontent.com/1926270/94296938-92e7e800-ff5b-11ea-9bc5-16b12bb490bd.png) |  ![screenshot-2020-09-24_19 33 14 533](https://user-images.githubusercontent.com/1926270/94186607-c9136200-fe9e-11ea-8bf0-ebb35e1a2a1d.png) ![screenshot-2020-09-24_19 32 13 585](https://user-images.githubusercontent.com/1926270/94186671-e2b4a980-fe9e-11ea-86fe-2ecd50937d30.png)  |

Improves visiblity of text and URLs in chat view.

---

app/build.gradle

This allows us to do bug fix releases while publishing new beta, 
eg. 8.0.10 and 9.0.0beta6

use new versionCode

---

.idea/misc.xml
app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatView.kt

Add missing import

---

app/build.gradle
app/src/main/res/values/colors.xml

Bump to 8.10.0 RC1

---

app/build.gradle

Bump to 8.1.0 release

---

.idea/misc.xml
.idea/modules.xml
app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
app/src/main/java/com/nextcloud/talk/models/database/User.java
app/src/main/java/com/nextcloud/talk/models/json/search/ContactsByNumberOCS.java
app/src/main/java/com/nextcloud/talk/models/json/search/ContactsByNumberOverall.java
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/java/com/nextcloud/talk/utils/AuthenticatorService.java
app/src/main/java/com/nextcloud/talk/utils/SyncAdapter.java
app/src/main/java/com/nextcloud/talk/utils/SyncService.java
app/src/main/java/com/nextcloud/talk/utils/database/user/UserUtils.java
app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
app/src/main/res/layout/controller_settings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/auth.xml
app/src/main/res/xml/contacts.xml
app/src/main/res/xml/syncadapter.xml

- set up in settings
- triggered every click on "+", but only once a day

Add phone book integration

---

app/build.gradle

Bump to 8.2.0

---

app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt

change email address for feedback

---

app/build.gradle
scripts/analysis/analysis-wrapper.sh

Fix classpath for Findbugs

---

scripts/analysis/analysis-wrapper.sh

Previously we uploaded it to findbugs-summary-master, but tried to access findbugs.html…

Correct location of findbugs summary

---

fastlane/Fastfile

Fix options for alpha upload via fastlane

---

.github/dependabot.yml

This will scan for dependencies that need an upgrade and creates a PR with label "3. to review".

Add DependAbot

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
app/src/main/java/com/nextcloud/talk/models/database/User.java
app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt
app/src/main/res/layout/dialog_attachment.xml
app/src/main/res/values/strings.xml

add ability to upload one or multiple files from local storage #254

---

app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatOCSSingleMessage.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatOverallSingleMessage.java
app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/res/drawable/ic_delete_white_24dp.xml
app/src/main/res/menu/chat_message_menu.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

add ability to delete messages

---

app/src/main/res/values/strings.xml

Changes that appeared in version 9.

Change text strings #458 , #817

---

README.md

from issue comment (= https://github.com/nextcloud/talk-android/issues/984#issuecomment-775172825 )

Added new alpha version download link in README.md

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
app/src/main/res/values-night/colors.xml
app/src/main/res/values/strings.xml

add confirm dialog before sharing files

---

scripts/analysis/lint-up.rb

Drone signs its comments

---

scripts/analysis/lint-up.rb

Drone signs its comments for master-broken

---

scripts/analysis/lint-up.rb

Use valid email address

---

CHANGELOG.md

create changelog (adapt to keepachangelog.com)

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/BrowserFile.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/DavResponse.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCEncrypted.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPreview.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCFavorite.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCId.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCSize.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/DavUtils.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFilesystemOperation.java

"Share from nextcloud" crashed. version update should be done when okhttp is bumped? https://stackoverflow.com/questions/39545629/noclassdeffounderror-failed-resolution-of-lokhttp3-internal-platform

revert dav4jvm to version f2078bc846

---

CHANGELOG.md
app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
app/src/main/java/com/nextcloud/talk/models/json/userprofile/UserProfileData.java
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/res/values/strings.xml

Phone number sharing

---

app/src/main/res/layout/rv_item_browser_file.xml
app/src/main/res/layout/rv_item_conversation_with_last_message.xml

I use and Nextcloud Talk on Android and I am personally affected by issue #955. This change seems to fix it.

Fix for display issues with non default font sizes (issue #955)

---

app/src/main/java/com/nextcloud/talk/controllers/CallController.java
app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
app/src/main/res/layout/controller_call_notification.xml
app/src/main/res/values/strings.xml

set application name in call screens from String nc_app_name

---

CHANGELOG.md
app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
app/src/main/res/values/strings.xml

fixPhonebookEntries

---

scripts/analysis/getBranchName.sh

@mahibi this needs to be done for every stable branch

BranchName needs to exclude v11.x

---

CHANGELOG.md
app/src/main/java/com/nextcloud/talk/components/filebrowser/adapters/items/BrowserFileItem.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/BrowserFile.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCEncrypted.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPermission.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCPreview.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCFavorite.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCId.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCSize.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/DavUtils.java
app/src/main/res/values/strings.xml

do not allow selecting files that are not allowed to be reshared

---

app/build.gradle

Unify (and update) dagger dependency version code(s)

---

app/src/gplay/AndroidManifest.xml
app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/res/drawable/launch_screen.xml
app/src/main/res/values/styles.xml

Add splash screen to Talk App

---

CHANGELOG.md
app/src/main/res/layout/controller_chat.xml

don't keep screen enabled in chat

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/no-response.yml
SECURITY.md

Signed-off-by: Joas Schilling <coding@schilljs.com>

Issue templates, security info and no-response

---

app/build.gradle

see $subject
Works on my device™️

Unify parceler version(s)

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

Show search bar when closing bottom sheet

---

app/build.gradle

something is still wrong here.
complains about wrong dependencies.
eg. something with "com.stfalcon.chatkit"
will have a look later
Fix #1197

replace forks: chatkit, fresco, popupBubble

---

app/src/main/res/values/strings.xml

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

l10n: Change to a capital letter

---

app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/CallController.java
app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java

* `no-ping` capability is set since Talk 4 from 2018 so the old workarounds are no longer needed
* `multi-room-users` capability is set since Talk 4 from 2018 so the old workarounds are no longer needed

🧹 Drop ping functionality

---

app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/controllers/CallController.java
app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
app/src/main/java/com/nextcloud/talk/jobs/DeleteConversationWorker.java
app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java

[apiv4] Add apiv4 for easy conversation api calls

---

app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
app/src/main/java/com/nextcloud/talk/controllers/CallController.java
app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java

[apiv4] ☎️ Calls

---

app/src/main/java/com/nextcloud/talk/controllers/CallController.java
app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java

Best reviewed as https://github.com/nextcloud/talk-android/pull/1235/files?w=1

[apiv4] 👤🏷️ Fix API calls for guests

---

.drone.yml
scripts/analysis/analysis-wrapper.sh
scripts/analysis/getBranchName.sh

run drone on stable-11 branch

---

app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt
app/src/main/res/values/styles.xml

make navigationbar for videocall black

---

app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java

Make observer type save

---

app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt

(were accidentally added in PR #1284)

remove toasts from worker

---

app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
app/src/main/res/drawable/account_circle_48dp.xml
app/src/main/res/layout/account_item.xml
drawable_resources/other/account-circle.svg

* in case of an error fetching the avatar, use a placeholder 
* use proper size for requesting avatar images

Set fallback avatar icon on account chooser

---

app/src/main/res/layout/controller_profile.xml

Follow-up for #1291 also adding the placeholder image on the profile view, plus some very, very minor optimizations regarding the layout itself

Add placeholder image to avatar for profile view

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java

Correct fix for not showing bold on read ConversationItem

---

.github/workflows/rebase.yml

shameless c&p from https://github.com/nextcloud/android/pull/8488 where it has been shamelessly copied from the desktop repo ;)

Rebase action: /rebase as comment

---

.github/workflows/fixup.yml

original by https://github.com/skjnldsv
replacement for the deprecated fixup bot in place before.

Block fixup and squash commits

---

app/src/main/res/layout/item_custom_incoming_text_message.xml
app/src/main/res/layout/item_custom_outcoming_text_message.xml
app/src/main/res/layout/item_message_quote.xml

Prevent text selection on messages

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
app/src/main/java/com/nextcloud/talk/utils/BitmapShrinker.kt

fix displaying of large images

---

app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/res/values/strings.xml

improve handling for missing location permissions

---

app/src/main/res/values/styles.xml

Fixes #1320
Test:
* Search on conversation list + text selection
* Search on location share + text selection

Correct text selection background

---

app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
app/src/main/res/values/strings.xml

Ref is https://github.com/nextcloud/spreed/pull/5670
But doesn't hurt to do this already

Add tracking circles support

---

app/build.gradle

bump master to 12.2.0 alpha1

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt

Check if attendeePin exists

---

app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt
app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java

[stable-12.1] temporarily disable logging to file

---

app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/res/values/strings.xml

set locationName to "Shared location" when geocoding failed

---

app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt

fix to expand attachment menu in landscape mode

---

CHANGELOG.md

update changelog for 12.1.0

---

app/src/main/res/values/strings.xml

Unbreak translations

---

app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java

Only parse baseURl if not empty

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt

Binding can be null due to async call

---

app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt

catch FileNotFoundException in copyFileToCache

---

CHANGELOG.md

update changelog for 12.1.1

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

Fixes #1415
Share from Google Chrome sets text/plain MIME type in the intent, but also provides a content:// URI with a **screenshot** of the current page in getClipData().
With this change we assume that when sharing a web page the user would prefer to send the URL of the current page rather than a screenshot.

Share from a browser should share the page URL

---

app/src/main/res/layout/controller_server_selection.xml

(to allow other ratios and sizes for customer logos. adapt to files app which allows all sizes)

remove logo dimensions for sever selection screen

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

Handle async call back to already destroyed UI

---

app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java

Base url can be null

---

app/src/main/res/values/styles.xml

Add item background for popup menu items

---

app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java

remove hardcoded api version for location sharing

---

CHANGELOG.md

update changelog for v12.1.2

---

app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
app/src/main/res/layout/controller_conversation_info.xml
app/src/main/res/values/strings.xml

- moderators can clear the chat in the conversations settings
- chat is cleared by system message CLEARED_CHAT
Fix #1336

add ability to clear chat history

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
app/src/main/res/values/strings.xml

Unify strings for clearing chat over all platforms

---

app/src/main/java/com/nextcloud/talk/ui/dialog/ScopeDialog.kt

expand privacy settings bottom sheet in landscape mode

---

app/build.gradle

Bump ImagePicker

---

CHANGELOG.md

update changelog for for 12.2.1

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
app/src/main/java/com/nextcloud/talk/webrtc/MagicAudioManager.java

Bump to SDK 30

---

docs/notifications.md

Signed-off-by: Joas Schilling <coding@schilljs.com>

Extend notification testing docs

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

Also account for unread 1on1 messages for unreadMessages bubbleClicked

---

docs/notifications.md

extend notification checklist

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

scroll to first unread mention and place it to the top

---

app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/DavUtils.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCard.java
app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCardAction.java
app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCardOCS.java
app/src/main/java/com/nextcloud/talk/models/json/hovercard/HoverCardOverall.java
app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/res/drawable/ic_talk.xml

Avatar "hovercard"

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java

bump version to 13.0.0 Alpha 1

---

app/build.gradle

bump version to 13.1.0 Alpha 01

---

app/src/main/res/layout/controller_settings.xml

Make all infos a subline

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/res/layout/call_activity.xml

fix to show call controls when connecting

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
app/src/main/java/com/nextcloud/talk/utils/ContactUtils.kt
app/src/main/res/drawable/ic_baseline_person_24.xml
app/src/main/res/layout/dialog_attachment.xml
app/src/main/res/values/strings.xml

resolve #1661 
Option | Contacts app taking over | Result
------- | -------- | --------

share contact from attachment dialog

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java

delete redundant if-check
cleanup of commit https://github.com/nextcloud/talk-android/commit/ca9a6220303760f9e1b5fdbd4cba56ace1a7e436

delete unused method leaveRoom

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
app/src/main/java/com/nextcloud/talk/utils/ContactUtils.kt
app/src/main/res/drawable/ic_baseline_person_24.xml
app/src/main/res/layout/dialog_attachment.xml
app/src/main/res/values/strings.xml

manual backport of 4167cb63bf04fdc56bfd4e279614dbe4a83ff040

share contact from attachment dialog (manual backport)

---

app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java

Some logging command to debug the calls. 
To filter the logs in Android Studio paste
`MagicFirebaseMessagingService|CallActivity|CallNotificationActivity|ChatController|NotificationWorker|MagicWebSocketInstance`
into the logcat search and activate 'regex' for it.

add logging for calls

---

app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

this will hangup:
- the call notification after 1 minute (the popup at the top)
- the call notification screen after 1 minute (the screen with the hangup and accept call buttons)

timeout call notification

---

app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

[stable-13.0] timeout call notification

---

CONTRIBUTING.md

Correct URL of branching diagram

---

app/src/main/res/values/strings.xml

backport translations from #1728 to stable-13.0

---

app/build.gradle

Bump android-gif-drawable from 1.2.23 to 1.2.24

---

docs/notifications.md

add link to dontkillmyapp.com

---

app/build.gradle

Bump okhttp to 4.9.3

---

app/build.gradle

Bump eventbus to 3.3.1

---

.github/dependabot.yml

... aligned with the version from android-files

Update dependabot script

---

.github/dependabot.yml

fix dependabot yaml formatting

---

.github/dependabot.yml

bump open pr count to 20

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
scripts/analysis/lint-up.rb

Download released WebRTC library from the [talk-clients-webrtc](https://github.com/nextcloud-releases/talk-clients-webrtc) repository.

Android update WebRTC library

---

app/src/main/java/com/nextcloud/talk/adapters/messages/MagicSystemMessageViewHolder.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt

add groups and circles to system messages ("add"+"remove")

---

.github/workflows/check.yml
app/build.gradle
app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
build.gradle
scripts/hooks/pre-commit
scripts/hooks/pre-push

adapting talk to https://github.com/nextcloud/android/pull/9977 changes

Use ktlint plugin instead of manual ktlint tasks

---

app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
detekt.yml

Use correct API endpoint for predefined status

---

app/build.gradle

bump master to 14.1.0 Alpha 1

---

app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java

Catch NPE when UI is already teared down

---

app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt

Fixes #1908 as an alternative, all-hardening approach to #1909

Move to a more hardened null-handling profile data handling

---

CHANGELOG.md

13.0.0 Changelog

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

avoid crash when clicking on header in conversation search mode

---

app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java

fix #1935 
| broken notification before (marcel2 reacted to "Hello")| fixed notification (also the "content title" is hidden)|
|---|---|
|![grafik](https://user-images.githubusercontent.com/2932790/164491589-83235012-4746-4245-8db7-423933fcfeed.png)|![grafik](https://user-images.githubusercontent.com/2932790/164491623-1572c511-8416-4f65-82c2-7cc2bbc62588.png)|

fix text for reaction notification + hide content title for one2one rooms and reactions

---

app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt

Fix npe if message has no self reactions initially

---

app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java

[Sorry](https://github.com/nextcloud/talk-android/pull/1886#discussion_r838083850) :-)

Fix typo in name of method to check if video should not be received

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

fix to load conversations when servers status app is disabled

---

app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
detekt.yml

PR #1969 is failing because of they are too much of them

Reduce number of Detekt issues

---

app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt

Always show reaction count

---

app/src/main/res/layout/activity_shared_items.xml

Hide shared items toolbar on scroll

---

app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt

Hide reactions from menu if conversation is read-only

---

app/src/main/java/com/nextcloud/talk/adapters/SharedItemsGridAdapter.kt
app/src/main/java/com/nextcloud/talk/adapters/SharedItemsListAdapter.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/MagicPreviewMessageViewHolder.java
app/src/main/java/com/nextcloud/talk/repositories/SharedItem.kt
app/src/main/java/com/nextcloud/talk/utils/DrawableUtils.kt
app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt

make attributes of file nullable and handle null values

---

app/src/main/java/com/nextcloud/talk/components/filebrowser/models/BrowserFile.java

Bugfix/1977/fix NPE in BrowserFile

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java

try to fix #1978
it's just a guess, see commit message..

Bugfix/1978/fix npe in peerConnectionWrapper

---

app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
detekt.yml

Hide actions reaction on deleted messages

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/models/database/CapabilitiesUtil.java

disable call buttons if calls are disabled by capability

---

app/src/main/java/com/nextcloud/talk/activities/SharedItemsActivity.kt
app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
app/src/main/java/com/nextcloud/talk/repositories/SharedItemsRepository.kt
app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt

DI: Setup viewmodel injection

---

app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/AudioOutputDialog.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ContactsBottomDialog.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ScopeDialog.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ShowReactionsDialog.kt
app/src/main/res/values/styles.xml

Make bottom_sheets initial state collapsed for the rounded top corners

---

app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
app/src/main/res/drawable/ic_baseline_notifications_off_24.xml
app/src/main/res/menu/chat_send_menu.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

resolve #1992
| Send without notification | Send without notification (dark)|
|---|---|
|![grafik](https://user-images.githubusercontent.com/2932790/168671649-35f7fbb3-c793-46af-80cd-691f28221f30.png)|![grafik](https://user-images.githubusercontent.com/2932790/168671760-3100c9a3-3ec5-4a28-95db-0d5f63bfea17.png)|

add silent send option

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java

Not needed anymore after #2061
Signed-off-by: Álvaro Brey <alvaro.brey@nextcloud.com>

Remove parceler annotation processor

---

gradle/wrapper/gradle-wrapper.properties

Bump gradle 7.3.3 -> 7.4.2

---

app/build.gradle

Revert compile sdk to 30

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
app/src/main/java/com/nextcloud/talk/utils/ContactUtils.kt
app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
app/src/main/java/com/nextcloud/talk/webrtc/MagicBluetoothManager.java

Bump compile sdk to 31

---

app/build.gradle

bump camera to 1.1.0RC01 and unify version info

---

app/build.gradle

Revert material back to 1.5.0

---

app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
app/src/main/java/com/nextcloud/talk/models/json/generic/GenericOCS.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt

fix  #2101
also seems to fix #2102
responses contain "ocs" which was deleted by aab00c5e8fef753c99033cbf048fcb5d2f11e602

Add GenericOCS

---

app/src/main/res/values/strings.xml

Override emoji search field hint text to be translatable

---

app/build.gradle

Bump androidxCameraVersion from 1.1.0-rc01 to 1.1.0-rc02

---

app/src/main/res/values/strings.xml

Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

i18n: Add a space

---

app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
app/src/main/java/com/nextcloud/talk/components/filebrowser/models/BrowserFile.kt
app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFolderListingOperation.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
app/src/main/java/com/nextcloud/talk/remotefilebrowser/adapters/RemoteFileBrowserItemsListViewHolder.kt
app/src/main/java/com/nextcloud/talk/remotefilebrowser/viewmodels/RemoteFileBrowserItemsViewModel.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
app/src/main/java/com/nextcloud/talk/utils/DrawableUtils.kt
app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
app/src/main/java/com/nextcloud/talk/utils/LoggingUtils.kt
app/src/main/java/com/nextcloud/talk/utils/Mimetype.kt

Centralize mime type definitions

---

app/src/gplay/java/com/nextcloud/talk/services/firebase/ChatAndCallMessagingService.kt
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/ui/dialog/AudioOutputDialog.kt
app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java

- Use log level exception for exceptions
- Make PendingIntent flag immutable
- Rename 'WebRtcAudioManger' to 'WebRtcAudioManager'
- Remove unneeded '@SuppressLint("InlinedApi")'
- Set PendingIntent flag immutable
- Use simple class name for logging
See https://github.com/nextcloud/talk-android/pull/2139#pullrequestreview-1016651339

Implement comments by PR #2139

---

app/build.gradle

Bump master to 14.2.0 Alpha 1

---

app/build.gradle

Bump androidx.camera from 1.1.0-rc02 to 1.1.0

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java

Resolves #2182
Picked from master where it has been fixed with the room  database layer

Nullcheck disposable

---

app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt

catch NPE for binding in toggleCallHeader

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

fix NPE for binding in onEmojiClickListener

---

app/build.gradle
app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt

Otherwise we can't install QA and normal app side by side
Follow up to #2148

Make private broadcast permission depend on applicationId

---

.drone.yml
scripts/analysis/analysis-wrapper.sh
scripts/analysis/getBranchName.sh

- Replace 'getBranchName.sh' with Git command
- Add stable branches as trigger for Drone
- Detect stable branches on the fly

Improvements to analysis scripts and Drone configuration

---

.devcontainer/Dockerfile

bump devcontainer to java11

---

app/src/main/java/com/nextcloud/talk/jobs/PushRegistrationWorker.java
app/src/main/java/com/nextcloud/talk/utils/PushUtils.java

...and its cookieStore
Resolves #2218
Issue had been introduced by #1776 

Push token recovery should not use the standard httpClient object 

---

app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/GeocodingController.kt
app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
app/src/main/java/com/nextcloud/talk/data/user/UsersDao.kt
app/src/main/java/com/nextcloud/talk/data/user/UsersRepository.kt
app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
app/src/main/java/com/nextcloud/talk/users/UserManager.kt
app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt

This PR migrates the remaining controllers from requery to room
* server selection
* web view login
* account verification
* location picker
* cleanup ChatController & GeocodingController

Migrate remaining controllers from requery to room

---

app/src/main/java/com/nextcloud/talk/utils/database/user/UserModule.kt

Organize imports

---

app/build.gradle
app/src/androidTest/java/com/nextcloud/talk/activities/MainActivityTest.kt
app/src/main/java/com/nextcloud/talk/data/user/UsersDao.kt
app/src/main/java/com/nextcloud/talk/data/user/UsersRepository.kt
app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
app/src/main/java/com/nextcloud/talk/jobs/WebsocketConnectionsWorker.java
app/src/main/java/com/nextcloud/talk/users/UserManager.kt
app/src/main/java/com/nextcloud/talk/webrtc/MagicProximitySensor.java

* remove unused persistence methods
* migrate to latest detekt report definition style

Persistence cleanup

---

app/src/main/res/drawable/ic_mimetype_video.xml

https://github.com/nextcloud/android/pull/10563

update video icon in line with files client 

---

app/src/main/java/com/nextcloud/talk/polls/adapters/PollCreateOptionViewHolder.kt
app/src/main/java/com/nextcloud/talk/polls/adapters/PollCreateOptionsAdapter.kt
app/src/main/java/com/nextcloud/talk/polls/adapters/PollResultVotersOverviewViewHolder.kt
app/src/main/java/com/nextcloud/talk/polls/ui/PollCreateDialogFragment.kt
app/src/main/res/layout/dialog_poll_create.xml
app/src/main/res/layout/dialog_poll_results.xml
app/src/main/res/layout/dialog_poll_vote.xml
app/src/main/res/layout/poll_create_options_item.xml
app/src/main/res/layout/poll_result_header_item.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml

📊 Polishing polls

---

build.gradle

Update AGP to 7.2.2

---

app/src/main/java/com/nextcloud/talk/polls/ui/PollMainDialogFragment.kt
app/src/main/res/values/strings.xml

Use singular and plural for vote(s) string

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

Make sure to set swipe-to-reply after the room info has been loaded

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java

Supplement to commit 546a174f4.
Resolves: #2302

Load higher resoliton avatars in conversation list (2)

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
app/src/main/java/com/nextcloud/talk/interfaces/ConversationMenuInterface.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt

* cleanup settings controller
* migrate any use to Material dialogs in conversation list controller

Remove lovely dialogs uses

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt

* Conversation info controller

Replace lovelyDialogs with Material 3 

---

app/build.gradle

Update to new home of forked libs

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

prevent NPE if UI has already been teared down

---

app/build.gradle

Update last forked lib reference to new home

---

app/src/main/res/values/strings.xml

1. Changing the style of the sentence.
2. Unifying the sentence with Talk Nextcloud https://github.com/nextcloud/spreed/pull/7790.
Signed-off-by: Valdnet <47037905+Valdnet@users.noreply.github.com>

i18n: Change style of sentence

---

app/build.gradle

bump version to 15.1.0 alpha1

---

app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
app/src/main/res/layout/activity_full_screen_text.xml

Theme toolbar for m3 for Text preview activity

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountShareToDialogFragment.kt
app/src/main/res/layout/dialog_choose_account_share_to.xml
app/src/main/res/menu/menu_conversation_plus_filter.xml
app/src/main/res/values/strings.xml

resolve https://github.com/nextcloud/talk-android/issues/1353
fix https://github.com/nextcloud/talk-android/issues/1981
single account | multiple accounts
-------- | -------- 

add account switcher for "share to"

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

this PR was created to find out what causes #2447
it didn't help for the issue, anyway it makes sense to get the toast in..

toast when Direct Video Upload fails to start

---

app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
build.gradle

bump kotlin to 17.0.20 and mark declaration usage as opt-in

---

app/build.gradle

Remove duplicate exifinterface dependency definition 

---

app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
docs/notifications.md

remove further codacy warnings

Housekeeping Part 2

---

app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt

This should avoid that the capabilities not available for the server EOL
check in 'ConversationListController#onAttach'.
Missing capabilites can also have an impact on multiple actions, but the
server EOL check is the first one.
Resolves: #2418

Use already fetched capabilities for user

---

app/src/main/java/com/nextcloud/talk/adapters/messages/LinkPreview.kt
app/src/main/res/layout/reference_inside_message.xml

before | after
-------- | -------- 

improve link preview design, add link description

---

CHANGELOG.md

- Correct header level for version 14.2.0
- Add version 15.0.0

Add version 15.0.0 to `CHANGELOG.md`

---

app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
app/src/main/java/com/nextcloud/talk/utils/AccountUtils.kt
app/src/main/res/layout/controller_server_selection.xml

simplify logic for server selection screen

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java

Fixes SPP_EQUALS_ON_ENUM issue from SpotBugs.
Even if it does not fix any user-facing bug it should be backported to avoid conflicts with other fixes.

Use comparison operator rather than equals for enums

---

app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java

[stable-15.0] Fix "isInCallWithVideo()" check

---

app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt

Show conversation search results first

---

.github/pull_request_template.md

add initial pull request template for github

---

CHANGELOG.md

update changelog for 15.0.1 + 15.0.2

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java

fix crash when joining call while silent ringtone is set

---

app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
app/src/main/java/com/nextcloud/talk/utils/remapchat/ConductorRemapping.kt
app/src/main/java/com/nextcloud/talk/utils/remapchat/RemapChatModel.kt
app/src/main/res/drawable/ic_baseline_error_outline_24dp.xml

manual backport of https://github.com/nextcloud/talk-android/pull/2620

Manual backport/bugfix/2181/fix conversation title

---

.github/workflows/analysis.yml
.github/workflows/assembleFlavors.yml
.github/workflows/autoApproveDependabot.yml
.github/workflows/check.yml
.github/workflows/command-rebase.yml
.github/workflows/fixup.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/qa.yml
.github/workflows/stale.yml

Add hashes to github action versions

---

CHANGELOG.md

Add 15.0.3 changelog

---

app/src/main/java/com/nextcloud/talk/adapters/items/GenericTextHeaderItem.java
app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
app/src/main/java/com/nextcloud/talk/utils/ssl/MagicTrustManager.java

...and as a consequence all experimental ones too

Spotbugs: fix all bad practice warnings

---

scripts/analysis/analysis-wrapper.sh

Analysis branch

---

.github/workflows/stale.yml

fix version comment

---

app/build.gradle

Bump version to 16.0.0

---

app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
app/src/main/java/com/nextcloud/talk/controllers/GeocodingController.kt
app/src/main/java/com/nextcloud/talk/controllers/LocationPickerController.kt
app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.kt
app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
app/src/main/java/com/nextcloud/talk/controllers/SwitchAccountController.kt
app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt
app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.kt
app/src/main/java/com/nextcloud/talk/controllers/util/ControllerViewBindingDelegate.kt

avoid crashes with NPEs for bindings

---

app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt

fix #2691
bug was introduced with fresco->coil migration
---|---

fix missing file icons in chat

---

CHANGELOG.md

update changelog for 15.1.1

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java

avoid NPE on hangup

---

.github/workflows/analysis.yml
.github/workflows/assembleFlavors.yml
.github/workflows/autoApproveSync.yml
.github/workflows/check.yml
.github/workflows/codeql.yml
.github/workflows/command-rebase.yml
.github/workflows/gradle-wrapper-validation.yml
.github/workflows/qa.yml
.github/workflows/scorecards.yml
.github/workflows/stale.yml

Update GH actions to latest master versions

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

hide scroll-to-bottom upon click

---

app/build.gradle

bump android common to 0.6.0

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

avoid NPE for voice message playback

---

app/src/main/res/values/strings.xml

l10n: Fix grammar

---

CHANGELOG.md

update changelog for 15.1.2

---

app/build.gradle

bump version to 16.1.0 Alpha 01

---

app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
app/src/main/res/drawable/baseline_error_24.xml

Show upload failed notification when failed normal upload

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
app/src/main/java/com/nextcloud/talk/models/json/converters/ConversationObjectTypeConverter.kt

Hide inactive breakout rooms from conversation list

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

Before it was requested every 5 sec even when not waiting in a lobby.
This is a first improvement to reduce requests. In a next step, more signaling messages should be handled to maybe even avoid recursive calls at all.

Request RoomInfo every 30 sec instead 5sec when not waiting in lobby

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
app/src/main/res/values/strings.xml

Restrict to join other rooms while being in a call

---

app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt

Add toast for debug mode if failed to get NC notification

---

app/src/main/res/values/strings.xml

fix string so build is possible again

---

app/src/main/res/layout/view_message_input.xml

Show keyboard at click on empty space

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

Fix rare crash when starting call

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java

Send raise hand signaling message.

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.kt
app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java

Hide call recording participant

---

app/build.gradle

Build(deps): Bump android-common from 0.6.0 to 0.7.0

---

app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java

Avoid NPE in loadAvatarImage

---

app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt

Avoid NPE in setupSwipeToReply

---

app/src/main/res/layout-land/activity_profile.xml

Split design for landscape editing/viewing a profile

---

app/build.gradle

to remove need of exclude config for arbitrary dependency

Bump ChatKit to 0.4.2 

---

app/src/androidTest/java/com/nextcloud/talk/ui/LoginIT.java
app/src/main/res/layout-land/activity_profile.xml
app/src/main/res/layout/controller_conversation_info.xml

Fix ci and new lint issues

---

CONTRIBUTING.md
README.md
app/src/main/res/values/strings.xml

https://help.nextcloud.com/t/transifex-announcement-web-applications-domain-change/159445
**Open Question:** @tobiasKaminsky @AndyScherzinger do we need also to adjust the `host` property in `.tx/config` for automated translations?

fix(i18n): Adjust links to transifex

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

Fix to scroll to first unread message

---

app/build.gradle

Bump main to 17.0.0 Alpha

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
app/src/main/res/drawable/ic_avatar_link.xml

partly revert #2997 to fix conversation avatars for NC26
---|---
B | A

fix conversation avatars for NC26

---

app/build.gradle

bump version to 17.1.0 Alpha 01

---

app/build.gradle

Build(deps): Bump com.fasterxml.jackson.core:jackson-core to 2.14.3

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
app/src/main/java/com/nextcloud/talk/activities/FullScreenTextViewerActivity.kt
app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
app/src/main/java/com/nextcloud/talk/translate/ui/TranslateActivity.kt

Resolves #2961
Signed-off-by: Ezhil Shanmugham ezhil56x.contact@gmail.com

Replace deprecated onBackPressed

---

app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt

File util fixes

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java

Fix code style for variable declaration

---

app/src/androidTest/java/com/nextcloud/talk/ui/LoginIT.java
app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItemNotifier.java
app/src/main/java/com/nextcloud/talk/call/CallParticipantModelNotifier.java
app/src/main/java/com/nextcloud/talk/signaling/CallParticipantMessageNotifier.java
app/src/main/java/com/nextcloud/talk/signaling/WebRtcMessageNotifier.java
app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java

Further code style improvements

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/TypingParticipant.kt
app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
app/src/main/java/com/nextcloud/talk/signaling/ConversationMessageNotifier.kt
app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
app/src/main/res/layout/activity_settings.xml
app/src/main/res/values/strings.xml

resolve https://github.com/nextcloud/talk-android/issues/3055

Align typing indicator to new concept

---

app/src/main/res/values/strings.xml

fix to avoid linebreak in strings.xml

---

.github/workflows/analysis.yml
.github/workflows/assembleFlavors.yml
.github/workflows/check.yml
.github/workflows/qa.yml

Follow-up for non standard actions, for details, see https://github.com/nextcloud/android-config/pull/73

Make actions cancelable

---

app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
app/src/main/res/layout/controller_server_selection.xml

fix to show error messages on server selection screen.
also resolve #3060

Show error messages on server selection screen & warn if talk is not installed

---

app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
app/src/main/res/layout/controller_server_selection.xml

fix lint issues recently introduced

---

app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt

Fix to show other errors than HttpException (e.g. ConnectException)

---

app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/res/layout/activity_conversation_info.xml

Quick conversation info bug fix

---

app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
app/src/main/java/com/nextcloud/talk/models/json/search/ContactsByNumberOCS.kt
app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
app/src/main/res/values/styles.xml

Fix phone book integration

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

backport of https://github.com/nextcloud/talk-android/pull/3161

avoid ArrayIndexOutOfBoundsException when swiping to reply.

---

app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt

avoid NPE in ProfileActivity because userInfo could be null

---

app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/EntryMenuController.kt

fix to be able to enter open conversation name

---

CHANGELOG.md

add 17.0.1 to changelog

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
app/src/main/java/com/nextcloud/talk/jobs/WebsocketConnectionsWorker.java
app/src/main/java/com/nextcloud/talk/models/json/websocket/RoomWebSocketMessage.kt
app/src/main/java/com/nextcloud/talk/utils/singletons/ApplicationWideCurrentRoomHolder.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt

followup to https://github.com/nextcloud/talk-android/pull/3177

minor Websocket fixes

---

app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
app/src/main/res/layout/activity_settings.xml
app/src/main/res/values/strings.xml

Translation string fixes

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/jobs/WebsocketConnectionsWorker.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt

Websocket improvements2

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/ui/MessageInput.kt
app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
app/src/main/res/drawable/baseline_stop_24.xml
app/src/main/res/layout/activity_chat.xml
app/src/main/res/layout/view_message_input.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml

fixes #2790 
[cont-voice-recording-new.webm](https://github.com/nextcloud/talk-android/assets/69230048/a4f55f4b-70b6-4924-90a8-bdcb4c0f8785)

Allow continuous recording and previewing of voice messages

---

CHANGELOG.md

add to 17.0.2 to changelog

---

app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt

Implement permission check for notifications on Android 13

---

app/src/main/res/layout/controller_conversations_rv.xml

Replace plus icon with pencil for main fab action

---

app/src/main/res/layout/activity_chat.xml

Resize chat headline to 18sp

---

app/build.gradle

Build(deps): Bump com.google.firebase:firebase-messaging to 23.2.0

---

app/build.gradle

Migrate to newer gradle sdk setting

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
app/src/main/res/layout/activity_full_screen_media.xml

Resolves #3152
This PR includes migration from ExoPlayer to Media3.

migrate to media3

---

app/build.gradle

resolve some tasks from https://github.com/nextcloud/talk-android/issues/2064
updated libraries hosted in jCenter

updated libraries hosted in jCenter

---

app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt

Removing unnecessary `Player.Listener`

Removing unnecessary Player.Listener

---

app/src/main/res/drawable/baseline_unfold_less_24.xml
app/src/main/res/drawable/baseline_unfold_more_24.xml

followup to https://github.com/nextcloud/talk-android/pull/3293

group system messages followup

---

.github/workflows/unit-tests.yml

Add unit test execution

---

app/src/main/java/com/nextcloud/talk/adapters/GeocodingAdapter.kt
app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
app/src/main/java/com/nextcloud/talk/viewmodels/GeoCodingViewModel.kt

**Implemented LiveData for GeoLocation RecyclerView**
https://github.com/nextcloud/talk-android/assets/99678760/0e772e34-5f77-4253-8f2e-40e8b90b5e84

use MVVM for Geocoding

---

app/build.gradle
app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt

fix emoji size in markdown headlines

---

app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
app/src/main/res/drawable/ic_note_to_self.xml

- fixes #786 
Joas already added the conversation, I just need to hide these UI elements
--- My Own TODO---

Note To Self ✏️ 

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt

Avoid Npe for call with a guest without name

---

app/build.gradle

Bump version to 18.0.0 Alpha 1

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenImageActivity.kt
app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenMediaActivity.kt
app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenTextViewerActivity.kt
app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/SaveToStorageDialogFragment.kt
app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
app/src/main/res/drawable/baseline_download_24.xml
app/src/main/res/layout/activity_full_screen_image.xml
app/src/main/res/layout/activity_full_screen_media.xml
app/src/main/res/layout/activity_full_screen_text.xml
app/src/main/res/layout/dialog_message_actions.xml
app/src/main/res/values-v27/styles.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

followup to #2331
credits also to [FaribaKhandani](https://github.com/FaribaKhandani) for the initial PR https://github.com/nextcloud/talk-android/pull/3416
Save option in context menu | Save option in fullscreen view | Warning dialog | Success info
------- | -------- | -------- | --------

followup changes to save file feature

---

app/src/main/res/layout/item_custom_incoming_preview_message.xml

File Caption Bug Fix - Bubble no longer under the user name

---

app/build.gradle

bump version to 18.1.0 alpha1

---

app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt

avoid crash when NC notification could not be retrieved

---

app/build.gradle
build.gradle

Update build files to latest DSL

---

app/src/main/res/layout/dialog_attachment.xml
app/src/main/res/layout/dialog_audio_output.xml
app/src/main/res/layout/dialog_conversation_operations.xml
app/src/main/res/layout/dialog_message_actions.xml
app/src/main/res/layout/dialog_message_reactions.xml
app/src/main/res/layout/dialog_scope.xml

Add drag handle to remaining bottom sheets

---

app/src/main/res/values/strings.xml

fix(i18n): Adapted trademarks and fixed grammar

---

app/build.gradle

bump version to 19.0.0 Alpha 01

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/res/values/strings.xml

follow up to #3630 
- Popup bubbles now show up
- Fixed bugs with images
- added new string resource

Follow up fixes to ChatActivity w/ recent refactoring

---

.github/workflows/pr-feedback.yml

Add SPDX header from sync

---

app/src/main/res/values/strings.xml

fix(i18n): Fixed case of word

---

.drone.yml
.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.yml.license
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml.license
.github/no-response.yml
.github/pull_request_template.md.license
LICENSES/Apache-2.0.txt
LICENSES/GPL-3.0-or-later.txt
LICENSES/MIT.txt
app/build.gradle
app/proguard-rules.pro
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
gradlew
gradlew.bat
renovate.json5.license
settings.gradle

Add SPDX header

---

.reuse/dep5

Add reuse dep5 package definition

---

.github/workflows/codeql.yml

Bump heap space

---

.editorconfig
.gitignore
.reuse/dep5
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
SECURITY.md
SETUP.md
app/src/gplay/AndroidManifest.xml
app/src/main/AndroidManifest.xml
detekt.yml
gradle/verification-keyring.keys.license
gradle/verification-metadata.xml.license
gradle/wrapper/gradle-wrapper.jar.license
spotbugs-filter.xml

SPDX header part2

---

app/src/main/res/layout/activity_settings.xml

https://github.com/nextcloud/talk-android/assets/111801812/71a6c11e-39cb-4a2d-8da4-2b99c0303cad
https://github.com/nextcloud/talk-android/assets/111801812/9341148f-1e85-4956-993e-8b9e61f70ab0

Retain Settings Screen Scroll State

---

app/src/main/res/drawable/ic_mimetype_text.xml

Update text mimetype color

---

app/build.gradle

bump version to 19.1.0 Alpha01

---

.reuse/dep5

Update SPDX headers

---

.idea/copyright/Nextcloud_Talk___Android_Client.xml
.idea/copyright/profiles_settings.xml

Add SPDX header template

---

.devcontainer/Dockerfile
.devcontainer/README.md

In sync with Android Files client.

Update devcontainer to jdk17

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/res/layout/dialog_message_actions.xml

Fix message delay on send and delete

---

app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/res/values/strings.xml

Resolves #3774 
(when internet is not connected)
---|---

Network checks and show network error dialog

---

app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/ui/bottom/sheet/ProfileBottomSheet.kt
app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt

avoid error when clicking on federated user avatar
avoid error when clicking on federated user mention chip

avoid error when clicking on federated user

---

app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
app/src/main/java/com/nextcloud/talk/callbacks/MentionAutocompleteCallback.java
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/events/CertificateEvent.java
app/src/main/java/com/nextcloud/talk/utils/CharPolicy.java
app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
app/src/main/java/com/nextcloud/talk/webrtc/ProximitySensor.java
app/src/main/java/com/nextcloud/talk/webrtc/WebRTCUtils.java
app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
app/src/main/java/com/nextcloud/talk/webrtc/WebRtcBluetoothManager.java

rename classes called 'Magic*'

---

app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt

fix visibility of leave conversation and delete conversation in ConversationInfoActivity

fix visibility of conversation options

---

app/src/main/AndroidManifest.xml

Set taskAffinity to empty value on application level

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

fix #3897
initMessageInputView() is called repeatedly when capabilities are received. This is not a good solution but was done because capabilities are needed inside initMessageInputView().
As sharedText is set inside initMessageInputView(), this caused the bug that text was repeatedly inserted in to the message input field.
All in all, there is only the need to initialize initMessageInputView() once. With this fix, it is for now done when there is no filter set yet. As a long term solution, the architecture must be changed so that initMessageInputView() is not called repeatedly, but all UI elements that need capabilities etc are updated by livedata. 
The fix should be seen as a quickfix for 19.0.1, but should be obsolete when architecture continues to improve..

fix to not set clipboard text repeatedly

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt

Follow up fix to refactoring

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

Editing a replied-to message no longer makes the reference to the original message disappear

---

renovate.json5

Fix typo in automerge attribute

---

app/build.gradle
renovate.json5

Block fido updates (again)

---

app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/res/layout/dialog_ban_actor.xml
app/src/main/res/layout/dialog_ban_participant.xml
app/src/main/res/values/strings.xml

see https://cloud.nextcloud.com/call/c7fz9qpr#message_3071670

Fix strings for banning

---

app/build.gradle
renovate.json5

Pin jackson core to 2.14.3

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
app/src/main/java/com/nextcloud/talk/data/database/dao/ConversationsDao.kt

manual backport of https://github.com/nextcloud/talk-android/pull/4069

Follow up bug fixes for offline support

---

app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt

fix #4168
1. Have some message with a hyperlink in chat that shows a preview.
2. While being in the chat, disconnect internet.
- Without this fix: Link preview is flickering
- With this fix: Link preview is not flcikering

do not try to pull chat messages when offline or paused

---

app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt

fix to show user status in conversation list

---

app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt

dont show error when fetching pending invitations failed

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt

fix #1747
Align with web on grouping messages.

group chat messages

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt

Message Queue bug fixes

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

fix crash when getting previousChatMessage

---

app/src/main/java/com/nextcloud/talk/api/NcApi.java
app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt

coroutine_5

---

.idea/inspectionProfiles/ktlint.xml
app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
app/src/main/java/com/nextcloud/talk/openconversations/adapters/OpenConversationsAdapter.kt
app/src/main/res/layout/activity_open_conversations.xml

Added a search bar to the "Join Open Conversations" screen

---

app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
app/src/main/java/com/nextcloud/talk/jobs/SaveFileToStorageWorker.kt
app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.kt
app/src/test/java/com/nextcloud/talk/json/ConversationConversionTest.kt
detekt.yml

Lower detekt score

---

app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt

Fixed Message draft overlayed icon bug

---

app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt

show message send button when there is text in input message field

---

app/src/main/res/values/strings.xml

fix translation for polls_option_delete

---

app/build.gradle

remove duplicated dependencies

---

app/src/main/res/values/strings.xml

Message count is an Int hence use 'd' not 's' as formatting character

---

app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt

check if scope is initialized before canceling

---

app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
app/src/main/java/com/nextcloud/talk/upload/normal/FileUploader.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
app/src/main/res/layout/activity_conversation_info.xml

Attach files to messages for fresh users

---

.github/workflows/assembleFlavors.yml
.github/workflows/check.yml
.github/workflows/qa.yml
.github/workflows/reuse.yml
.github/workflows/unit-tests.yml

ci: Update workflows

---

app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
app/src/main/res/layout/call_activity.xml

fix #4797
This PR will make sure necessary permissions are granted before starting the call at all
**STR:**
- have no permissions granted for android app
- call from web to android
- grant permissions while joining the call
**Without this PR:**
Audio is not sent from android to web
**With this PR:**
Audio is sent to web
- please test the STR described above
- please test all different call scenarios that come to your mind in terms of permissions

Fix sound after mic permission was granted

---

app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt

show full open conversation list when search text is empty

---

app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
app/src/main/java/com/nextcloud/talk/dagger/modules/ViewModelModule.kt
app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseContentComposable.kt
app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseViewModel.kt
app/src/main/java/com/nextcloud/talk/models/json/testNotification/TestNotificationData.kt
app/src/main/java/com/nextcloud/talk/models/json/testNotification/TestNotificationOCS.kt
app/src/main/java/com/nextcloud/talk/models/json/testNotification/TestNotificationOverall.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
app/src/main/res/values/strings.xml

Test notifications

---

app/src/main/res/layout/activity_conversation_info.xml

fix conversation description position

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/res/values/strings.xml

update snackbar text

---

app/src/main/res/drawable/baseline_article_24.xml
app/src/main/res/drawable/baseline_audiotrack_24.xml
app/src/main/res/drawable/baseline_bar_chart_24.xml
app/src/main/res/drawable/baseline_block_24.xml
app/src/main/res/drawable/baseline_contacts_24.xml
app/src/main/res/drawable/baseline_image_24.xml
app/src/main/res/drawable/baseline_mic_24.xml
app/src/main/res/drawable/baseline_video_24.xml

Use correct license header for Material icons

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

make snackbar clickable

---

app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
app/src/main/java/com/nextcloud/talk/models/json/profile/CoreProfileAction.kt
app/src/main/java/com/nextcloud/talk/models/json/profile/Profile.kt
app/src/main/java/com/nextcloud/talk/models/json/profile/ProfileOCS.kt
app/src/main/java/com/nextcloud/talk/models/json/profile/ProfileOverall.kt
app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
app/src/main/res/layout/activity_conversation_info.xml
app/src/main/res/values/strings.xml

- fixes #4714 
| Full | Role only |
|--------|--------|
| ![Screenshot 2025-05-16 at 1 55 08 PM](https://github.com/user-attachments/assets/98a61bd4-ebb9-4c1a-aa16-d56ebea58c97)| ![Screenshot 2025-05-16 at 1 53 58 PM](https://github.com/user-attachments/assets/06bc716f-2057-44dd-9c12-da1e0f662296)
|

👤 Improving right sidebar 

---

app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/java/com/nextcloud/talk/models/json/conversations/ConversationEnums.kt
app/src/main/java/com/nextcloud/talk/models/json/converters/ConversationObjectTypeConverter.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
app/src/main/res/layout/activity_chat.xml
app/src/main/res/layout/item_event_schedule.xml
app/src/main/res/layout/remainder_to_delete_conversation.xml
app/src/main/res/values-night/colors.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml

Resolve #4968 
Resolve issues in comments https://github.com/nextcloud/talk-android/pull/4846#discussion_r2089246609 https://github.com/nextcloud/talk-android/pull/4846#discussion_r2089248846 https://github.com/nextcloud/talk-android/pull/4846#discussion_r2089242322

Improvements event conversations

---

app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
app/src/main/java/com/nextcloud/talk/utils/Mimetype.kt

- fixes #4941 
also themes the lock conversation switch

Allows .HEIC files to be opened in app

---

app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/15.json
app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
app/src/main/java/com/nextcloud/talk/data/database/mappers/ConversationMapUtils.kt
app/src/main/java/com/nextcloud/talk/data/database/model/ConversationEntity.kt
app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
app/src/main/java/com/nextcloud/talk/models/domain/ConversationModel.kt
app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
app/src/main/res/layout/item_notification_settings.xml
app/src/main/res/values/strings.xml

Resolve #4964
no message preview in notification | no message preview in conversations list
--- | ---

Allow to mark conversation as sensitive

---

app/src/main/java/com/nextcloud/talk/contacts/ContactsScreen.kt
app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
app/src/main/java/com/nextcloud/talk/contacts/components/AppBar.kt
app/src/main/java/com/nextcloud/talk/contacts/components/ContactItemRow.kt
app/src/main/java/com/nextcloud/talk/contacts/components/SearchComponent.kt
app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
app/src/main/res/values/strings.xml

Resolve #4886
Also resolve https://github.com/nextcloud/talk-android/pull/4898#issuecomment-2910369602

"Add" button to add participants

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/res/layout/item_event_schedule.xml
app/src/main/res/layout/remainder_to_delete_conversation.xml

follow up to https://github.com/nextcloud/talk-android/pull/4969

UI improvements to automatic conversation deletion information for event, sip and instant meetings conversation

---

app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
app/src/main/java/com/nextcloud/talk/bottomsheet/items/ListIconDialogAdapter.kt
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenMediaActivity.kt
app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
app/src/main/res/values/strings.xml

Adding a short cut to note-to-self

---

app/build.gradle
renovate.json5

bump jackson core version

---

app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt

Scale DatePicker for smaller screens

---

app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt

🎨 Update searchbar to m3 theming

---

app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt

Bug in user status dialog

---

app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt

avoid NPE crash in conversation list

---

app/src/androidTest/java/com/nextcloud/talk/data/database/dao/ChatBlocksDaoTest.kt
app/src/main/java/com/nextcloud/talk/account/BrowserLoginActivity.kt

I didn't use the correct polling url 😔

Fixed Login V2 Bug

---

app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingDeckCardViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
app/src/main/java/com/nextcloud/talk/chat/MessageInputVoiceRecordingFragment.kt
app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt

- more progress to resolve https://github.com/nextcloud/talk-android/issues/3074
Implement to answer to a message with a file.
This is especially needed for threads, where we answer to the first message of the thread (but for this case, we won't show the quoted message).
This also enables to answer with a file to chat messages in a normal chat, although it might not completely covered by all message types in UI yet (could be checked for followup PRs or wait for migration to Compose).

answer with files

---

app/src/main/res/values/styles.xml

Ensure mention chips are chat-text text-sized

---

.idea/codeStyles/Project.xml
app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt

Allowing Login by QR code after reverting to Login v1

---

app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt

don't group system messages over date separator

---

app/src/main/java/com/nextcloud/talk/threadsoverview/components/ThreadRow.kt

styled(threads): Align threads overview style with web UI
