- app/src/main/res/values/strings.xml
Previously looked like this on TX:
"Permissions need to be granted to establish a video and/or audio call. Please
click \"ALLOW\" in the upcoming system dialog."
> Odd newlines cleaned up

- app/src/main/res/layout/bottom_sheet.xml
- app/src/main/res/layout/controller_bottom_navigation.xml
which help's with the contrast since standard window background color is a light grey and combined with the grey 600 headlines and icons leads to a lowered contrast. Thus changing the background color.
> make bottom sheets' background white

- app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
- app/src/main/res/layout/controller_call_notification.xml
- app/src/main/res/values-land/dimens.xml
- app/src/main/res/values/dimens.xml
* slightly lower the call notification avatar size, 
* optimize for layout to work for portrait and landscape
The avatar is still quite large in landscape, so the `dimens` value could be lowered to `140dp` or `120dp` and should still look okay fort portrait.
> Fix call notification layout for landscape

- app/src/main/res/values/strings.xml
When using the 3-dot-menu for a conversation, it only needs to show the conversation name in the title. "Configure conversation" before that is not necessary.
(Also detail fix »Change a password« → »Change password«)
> Fix wording details

- gradle/wrapper/gradle-wrapper.properties
mirroring https://github.com/nextcloud/android/pull/2845 to the talk repo
> see https://github.com/nextcloud/passman-android/pull/52 or https://gitlab.com/fdroid/rfp/issues/199 respectively. 
> 
> So for security reasons it makes sense to have the checksum added to the wrapper properties.
> add checksum for gradle release

- app/src/main/res/layout/rv_item_conversation_with_last_message.xml
Resolves #320 - setting a fixed line number of 2
+ aligning avatar and unread count at the top
+ adding IDE preview rendering infos
Not 100% sure this is what has been described in #320 and if it covers all areas referred to in the issue so please have a look :)
_______
> Height of conversations in list should all be the same

- .idea/compiler.xml
- app/src/main/java/com/nextcloud/talk/utils/PushUtils.java
Connections, streams, files, and other classes that implement the Closeable interface or its super-interface, AutoCloseable, needs to be closed after use. Further, that close call must be made in a finally block otherwise an exception could keep the call from being made. Preferably, when class implements AutoCloseable, resource should be created using "try-with-resources" pattern and will be closed automatically.
Failure to properly close resources will result in a resource leak.
> utils: use try-with-resources to properly close Closable.

- app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
Using the same value on either side of a binary operator is almost always a mistake. Either there is supposed to be a null check for something else in there or the second sub expression should be removed.
> controllers: removed identical sub-expression in if statement.

- app/build.gradle
'compile' is obsolete and has been replaced with 'implementation' and 'api'.
> gradle: replace use of obsolete 'compile' configuration.

- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
There is no real need to use a custom limit, when the server has a sane default as well as a setting to overwrite this.
> Use server default value for autocomplete limit

- app/src/main/java/com/nextcloud/talk/utils/ssl/MagicKeyManager.kt
Unfortunately I couldn't verify the problem or test the fix on this branch. The login GUI seems to be somewhat broken currently due to refactoring process (no option for client certificates showing).
But looking at the code, the master branch has a similar problem in the logic as v.8.0.x which I addressed in PR #746.
Signed-off-by: Stephan Ritscher <no3pam@gmail.com>
> Handle client certificate alias if currentUser is null (relates to #195)

- app/src/main/java/com/nextcloud/talk/components/filebrowser/controllers/BrowserController.kt
- app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
- app/src/main/java/com/nextcloud/talk/newarch/features/account/serverentry/ServerEntryView.kt
- app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatPresenter.kt
- app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatView.kt
- app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/call_item.xml
- app/src/main/res/layout/call_states.xml
- app/src/main/res/layout/contacts_list_view.xml
- app/src/main/res/layout/controller_account_verification.xml
- app/src/main/res/layout/controller_browser.xml
- app/src/main/res/layout/controller_call_menu.xml
- app/src/main/res/layout/controller_chat.xml
- app/src/main/res/layout/controller_entry_menu.xml
- app/src/main/res/layout/controller_locked.xml
- app/src/main/res/layout/controller_operations_menu.xml
- app/src/main/res/layout/conversations_list_view.xml
- app/src/main/res/layout/message_state.xml
- app/src/main/res/layout/new_group_conversation_view.xml
- app/src/main/res/layout/rv_item_app.xml
- app/src/main/res/layout/rv_item_browser_file.xml
- app/src/main/res/menu/menu_conversation.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values-v21/styles.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
Status bar and navigation bar theming
Misc fixes for UI elements to bring them inline with the status bar and
nav bar colours.
Addresses issue #860. 
Ready for review. Screenshots:
Signed-off-by: Daniel Bailey <daniel.bailey@grappleIT.co.uk>
> Status bar and navigation bar theming

- app/src/main/java/com/nextcloud/talk/controllers/CallController.java
- app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
- app/src/main/java/com/nextcloud/talk/webrtc/MagicWebSocketInstance.java
This pull request adds avatars for guests in the call view, as well as fixing other related issues. For details please refer to the individual commit messages :-)
It will probably need to be forwardported, although I have not checked.
Also note that the avatar is currently shown only for guests for which there is a peer connection (as the guest avatar depends on the nick, and the nick for guests when the HPB is used is currently sent through data channels, which require a peer connection). None of the changes from https://github.com/nextcloud/spreed/pull/4182 are applied here.
- Setup the HPB
- Create a public conversation
- With the Android app, join the public conversation
- With a browser, join the public conversation as a guest
Nothing strange happens.
The web socket of the Android …
> [v8.0.x] Fix some issues related to guest participants

- app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
When another participant shared the screen a new offer was requested. However, the offer was requested for the video instead of for the screen, which caused the HPB to stop the previous video connection and replace it with a new one. As receiving new offers for an existing connection is not properly handled the offer was applied to the existing peer connection, which caused the new offer to be ignored and the old peer connection to be kept (but frozen due to the HPB not sending more data for that connection).
Requesting offers are not needed when the peer connection is a screen, as the HPB will automatically send the offers itself. Therefore, now offers are requested only when the connection is of `video` type.
It will probably need to be forwardported, although I have not checked.
Note …
> [v8.0.x] Fix frozen video when screen is shared

- app/src/main/java/com/nextcloud/talk/newarch/features/chat/ChatView.kt
When returning to a chat window from the conversation info screen
the focus will stay at the bottom of the page, i.e. the most recent.
I _think_ this will fix #826 and haven't seen any unintentional side effects in my testing. 
Signed-off-by: Daniel Bailey <daniel.bailey@grappleIT.co.uk>
> ChatView scrolling fix

- app/src/main/java/com/nextcloud/talk/webrtc/MagicPeerConnectionWrapper.java
See https://github.com/nextcloud/spreed/issues/3937
It will need to be forwardported.
Please note that, although the changes should work as expected, I have **not** tested this pull request. 
The HPB includes a patched Janus version, so it is not possible to test this against our cloud or the Talk testing server. This must be tested against _nextcloud-spreed-signaling_ paired with an upstream Janus package >= 0.7.0 (for example, the default Janus package from Ubuntu Focal (20.04), which is Janus 0.7.3). Unfortunately I can not do that from the machine with the Android development environment.
Also note that [the initial media status is still sent only when the `status` data channel is opened](https://github.com/nextcloud/talk-android/blob/6a5aaac2244aa207aae39a033dba170d257dbb29/app/src/ma …
> [v8.0.x] Fix data channel suport with newer Janus versions

- fastlane/Appfile
- fastlane/Fastfile
This is needed for alpha version builds.
It can be later enhanced to also build beta/rc and deploy it automatically to Gplay/Fdroid.
> Add basic support for Fastlane

- app/build.gradle
2.0.1 leads to error so the app won't start. will be bumped later
> revert flexbox to 1.1.0

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
On current master
- have only one unread conversation in bold
- scroll up/ down
- see other unrelated conversation also in bold
--> on recyclerview items are recycled, thus the state also persists, so we have to set them explicitly.
> On Recyclerview everything needs to be set explicitly

- app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
- app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ProfileController.java
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
- app/src/main/java/com/nextcloud/talk/models/json/converters/EnumParticipantTypeConverter.java
- app/src/main/java/com/nextcloud/talk/models/json/participants/Participant.java
- app/src/main/res/layout/controller_conversation_info.xml
- app/src/main/res/layout/controller_profile.xml
- app/src/main/res/layout/controller_settings.xml
- app/src/main/res/layout/rv_item_conversation_info_participant.xml
- app/src/main/res/layout/rv_item_conversation_with_last_message.xml
- app/src/main/res/layout/rv_item_mention.xml
- app/src/main/res/layout/search_layout.xml
- app/src/main/res/layout/user_info_details_table_item.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/xml/chip_others.xml
Resolves #1129
Also 
* removes the dark-blue-grey headline color and replaces any occurrences with high-emphasis text color except for the chat bubbles, they have been kept as is for now (might change with a separate PR)
* Sorts the participants list in a hierarchical way: ownership, online, moderator, displayname (like the webUI)
* WCAG optimizations regarding inactive icons, hitbox size of min=48dp
* don't make toolbar menu item text all-caps
|Settings|User profile|
|---|---|
|<img width="540" alt="device-2021-04-14-184344" src="https://user-images.githubusercontent.com/1315170/114748014-bcc6f780-9d51-11eb-9f62-66bb67893d5d.png">|<img width="540" alt="device-2021-04-14-231748" src="https://user-images.githubusercontent.com/1315170/114780435-b186c280-9d77-11eb-8ca3-c8f3037f6d67.png">| …
> Accessibility participants list and grey tones

- app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
I have just tested the new image preview - works great... :smiley: Thanks!
However I have found that sometimes it would be good to be able to enlarge the image more than the default 3x set in the PhotoView library. This applies esp. when posting photos directly from the phone.
This change enables zooming the image 6x rather than just 3x. Since the default double-tap handler uses the max/medium scale parameter, I have also adjusted the mediumScale to make double-tab more consistent/predictable.
> Enable enlarging the image more than default 3x maximumScale.

- app/src/main/res/layout/controller_chat.xml
(also in dark mode)
found by @nickvergessen and fixed via this PR. The unread messages text should always be white-colored no matter the theme
Issue:
> Make sure "unread messages" bubble text is always white 

- app/build.gradle
- build.gradle
* bump to 1.3.2
For (short) info about the move see: https://mvnrepository.com/artifact/javax.annotation/jsr250-api
> jsr250 lib has moved from annotation to annotation-api

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/adapters/messages/MagicIncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/MagicOutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
successor of #1126
* unifies the version code for all coil-libs
* updates code to new coil API
svg/gif loading have been tested via the chat messages where coil is utilized
> Bump coil to 1.2.0

- app/build.gradle
Starting from [Kotlin 1.4](https://kotlinlang.org/docs/whatsnew14.html#dependency-on-the-standard-library-added-by-default) the dependency on the standard library added by default. So a follow-up task due to #1148
> Remove kotlin-stdLib since it is added by default since kotlin 1.4.x

- app/src/main/res/layout/rv_item_title_header.xml
> Align contact category headlines

- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
- app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
- app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
- app/src/main/res/values/strings.xml
1. Setup an account in the mobile app
2. In the web UI revoke the device token
3. In the app pull down to refresh the conversation list
⬜️ or ⬛  Nothing happens
* A dialog asks whether the account:
+  Should reauthenticate and enter a new password
+ The account should be deleted
* remove the account instead of being stuck in a loop to reauth.
* switch to another account or create another one
> Start the reauth webview also when there is no getParentController()

- app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/NCEncrypted.java
- app/src/main/java/com/nextcloud/talk/components/filebrowser/models/properties/OCFavorite.java
encryption and favorite property are delivered via 0/1 values not TRUE/FALSE thus the parser needs to check for that.
To test simply have files on your Nextcloud marked as favorite and try to add a file via Nextcloud in the chat. 
Before: No start icon
After: star icon
> Properly parse encryption/favorite flags

- app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
- app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
- app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
- app/src/main/java/com/nextcloud/talk/controllers/CallController.java
- app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
- app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
- app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/OperationsMenuController.java
- app/src/main/java/com/nextcloud/talk/jobs/AddParticipantsToConversation.java
- app/src/main/java/com/nextcloud/talk/jobs/DeleteConversationWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/LeaveConversationWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
- app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
- app/src/main/java/com/nextcloud/talk/utils/NoSupportedApiException.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
- app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
So there are quite some breaking changes with the upcoming APIv4 of the Talk server for Nextcloud 22, most of all it's multiple sessions per participant.
So I wanted to check and help migrating to APIv4, and now I wonder how we want to do this even.
As you can see in this PR there is one place which has duplicate logic for APIv3 and APIv1 already.
to deduplicate some logic and e.g. not have getRoom, getRoomV3, getRoomV4 functions and further on multiplying all methods in ApiUtils.java like e.g. getUrlForParticipants, I wonder if the version should be an (or even the first) argument to all the methods instead.
Also instead of code like:
```java
boolean isConversationApiV3 = userBeingCalled.hasSpreedFeatureCapability("conversation-v3");
boolean isConversationApiV4 = …
```
> v4️⃣ - Add option for APIv4 compatibility

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
- app/src/main/java/com/nextcloud/talk/adapters/items/UserItem.java
- app/src/main/res/drawable/ic_circular_mail.xml
- drawable_resources/other/circular_mail.svg
in the greyed out state (!)
light|dark
---|---
...also fix conversation names visible when switching themes (without an app restart)
> ✉️ Add mail icon for mail users

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Manual backport and theme switch follow-up PR.
Besides the conversation name also the unread messages bubble/text haven't refreshed properly (the unread, but no mentions bubble as-in grey, not blue)
> [backport] set proper colors for unread-messages for edge case of theme switch

- app/build.gradle
necessary to fix version-code for playstore
> bump alpha version to "12.0.0 Alpha 11"

- app/src/main/res/values/strings.xml
Due to our poor mans XML concatenation new lines are not kept and cause invalid XML. See https://github.com/nextcloud/docker-ci/pull/280/files#diff-9d28cba068f86de5b086c8b5e7ba5e44df1f4d5d299421e2bf5eb168551af078R68 for the XML concatenation. THis is a quick fix and better should be handled by just properly parse and combine the XML.
Found after https://github.com/nextcloud/docker-ci/pull/280 
cc @AndyScherzinger @tobiasKaminsky
> Remove new line from translatable string

- app/src/main/res/values/strings.xml
... since linter config should already cover this
> remove ExtraTranslation flags

- app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
- app/src/main/res/layout/rv_item_mention.xml
due to a recent change the mentioned pop-up when typing a message is also dark for dark themes. Unfortunately the list items header line text was black which worked for light but not dark theme. This PR fixes it by setting the color explicitly and using "the right" context (which is the activity's context _not_ the application contenxt).
> Use proper activity context to grab themed color for mentions

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
fix  #1281 
deletion for attachments in talk is not supported by server. Because of this the delete option must be suppressed in the available options when the user long clicks next to an attachment.
> dont show deletion option for attachments

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/ui/recyclerview/MessageSwipeActions.kt
- app/src/main/java/com/nextcloud/talk/ui/recyclerview/MessageSwipeCallback.kt
- detekt.yml
...for chat messages (incoming/outgoing/preview).
Thanks to the magnificent work of @shainsingh89 with https://github.com/shainsingh89/SwipeToReply and his permission to use parts of his code to implement this feature for Nextcloud Talk. Here it is "swipe right to reply"
* adds a short vibration on swipe target
* message flings back into its original position
Again except for the actual reply message built-up and some very minor code changes to make kotlin happy all the swipe-magic is the work of @shainsingh89 🥇 
---
**Screenshots**
:new_moon_with_face: dark|:sun_with_face: light
---|---
> Swipe-right to reply 

- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
* Always fallback to the guest avatar instead of none 
* Show the bridge-bot avatar for bridged messages (ref https://github.com/nextcloud/spreed/pull/5667 )
> Fix avatar handling

- app/src/main/res/layout/controller_chat.xml
- app/src/main/res/layout/item_custom_incoming_text_message_shimmer.xml
Before we had a centered, circular spinner which is now replaced by shimmer messages, like we use in other places in the app already and also like we do on the web UI:
> Add shimmer for chat content loading

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Catch IllegalStateException in case EmojiCompat hasn't been initialized yet, hit more than 700 users, already present in v11
Fixes #1371
> Harden Chat Title Calculation

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/res/layout/controller_chat.xml
- app/src/main/res/layout/view_message_input.xml
- app/src/main/res/values-night/colors.xml
Based on the accessibility scanner regarding the chat view: 
**Hitbox-Size**
* Single line message
* com.nextcloud.talk2:id/attachmentButton
* com.nextcloud.talk2:id/smileyButton
* com.nextcloud.talk2:id/messageInput
* com.nextcloud.talk2:id/recordAudioButton
40dp - should be at least 48dp
**Text-Contrast**
* com.nextcloud.talk2:id/messageTime
contrast 3,13 - should be 4,50
* com.nextcloud.talk2:id/messageAuthor
contrast 2,72 - should be 4,50
**Text-Contrast**
* com.nextcloud.talk2:id/messageText
contrast 4,17 - should be 4,50
I fixed most of the issue by
* using a darker color for the incoming message chat bubbles - before `#484848` now at "6dp elevation" `#1CFFFFFF`, see https://material.io/design/color/dark-theme.html#properties for details
* raised the size of the message input icons …
> Improve Chat Accessibility

- app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.java
- app/src/main/java/com/nextcloud/talk/controllers/CallController.java
- app/src/main/java/com/nextcloud/talk/controllers/CallNotificationController.java
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ContactsController.java
- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
- app/src/main/java/com/nextcloud/talk/controllers/LockedController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.java
- app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
- app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.java
- app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.java
- app/src/main/java/com/nextcloud/talk/controllers/base/NewBaseController.kt
- app/src/main/java/com/nextcloud/talk/controllers/bottomsheet/CallMenuController.java
- app/src/main/java/com/nextcloud/talk/dagger/modules/DatabaseModule.java
- app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/controller_conversations_rv.xml
- app/src/main/res/layout/controller_locked.xml
- app/src/main/res/layout/controller_server_selection.xml
- app/src/main/res/layout/controller_settings.xml
- app/src/main/res/values/setup.xml
- app/src/main/res/xml/auth.xml
- app/src/qa/res/values/setup.xml
shorten app label Nextcloud Talk -> Talk while keeping "Nextcloud Talk" as a label within the app itself
**TODO**
_Brander needs to adapt to additional string in ```setup.xml```_ 
ping @tobiasKaminsky for details on the brander.
❗ **Should only be backported to 12.1 _if_ the brander is going to support it within the next days** ❗
I suggest to postpone this to 12.2 (at least), also cc @nickvergessen since this PR creates a change demand for brander - to be managed/timed
> Shortened launcher label

- app/src/main/java/com/nextcloud/talk/controllers/CallController.java
When processing the participants in a room the signaling sessions of the participants were compared against the Nextcloud session of the local participant to find out which were the remote sessions. However, when the HPB is used the signaling session is not the same as the Nextcloud session, so the signaling session of the local participant never matched her Nextcloud session, so it was always seen as a remote participant.
This caused the call state to be changed to `in conversation` (which, for example, stopped the calling sound), when only the local participant was in the call.
- Setup the HPB
- Open the Talk Android app from scratch (otherwise currently there could be dangling sessions, something to be fixed later)
- Open a conversation
- Start a call
The calling sound plays.
The …
> Fix own peer handling when HPB is used

- .editorconfig
If an developer have a own '.editorconfig' in some location above the repostires
directory it will used in the gradle build and formatting checks can be fail.
To avoid this an get an more uniform code style between Nextclouds Android apps
the '.editorconfig' from the Nextcloud Android app is used.
Because of defining 'root=true' the developers own '.editorconfig' is not used
anymore.
> Add missing .editorconfig

- app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
Call notifications don't work with a 22+ server
First you see this in the console log:
> Api call did not try conversation-v4 api
And afterwards the notification is killed with
> NoSupportedApiException
> Fix call notifications

- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
Fix #1429
Not sure what my head did, but there was no `conversation` capability ... ever...
https://github.com/nextcloud/spreed/blob/master/docs/capabilities.md#40
So now we use `mention-flag` which is influencing the conversation api and a anti-check for api-v4 as v1 routes are there all that time.
Might need to bump this to also exclude future versions, if v5 would drop v4 e.g.
> Fix capability check for 14-18

- app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
Before the app stopped ringing when:
* participant list is empty or
* the participant list is empty and you are in the participant list (never true, because either it's empty of you are a part of it)
> Fix the check if user joined on another device

- app/src/main/res/layout/controller_conversation_info.xml
Set attribute 'andorid:autoLink' to 'all' for converting all possible
urls (email, map, phone, web) to clickable links.
Resolves: #1243
> Make links clickable in conversation description

- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.java
- app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
The new system message types 'call_missed' and 'call_tried' should be
shown as system messages and not regular text messages.
Resolves: #248
> Add new system message types

- app/src/main/res/layout/view_message_input.xml
this will fix that voice messages can be recorded. only set the text input to layoutDirection=locale
> set layoutDirection for message input panel to ltr. 

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
this will fix to hide the delete-button when the message is not from the current user and the user not a moderator.
see https://nextcloud-talk.readthedocs.io/en/latest/chat/#deleting-a-chat-message
before the delete option was shown even if the user was only the owner. When tapping on "delete", an error 403 was received.
> fix displaying of message delete-button

- app/src/main/java/com/nextcloud/talk/activities/MagicCallActivity.kt
show the lockscreen when switching to chat in a call that was opened by notification before the phone was unlocked.
> enable keyguard for toggle chat

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/utils/DateUtils.kt
- app/src/main/res/layout/lobby_view.xml
- app/src/main/res/values/strings.xml
resolve #1557
I didn't get it the way like in [iOS](https://github.com/nextcloud/talk-ios/pull/615#issue-987829178). So stay with the timer like in spreed. Is that OK?
Days | Hours | Minutes | Soon
------- | -------- | ---------- | --------
> Show lobby timer and description in lobby screen 

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.java
resolve #1559 
differentiate unread counters for group mentions and direct mentions
before | after (server with new capability) | after (server without new capability)
------- | -------- | ---------- 
> differentiate unread counters

- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
fix #1596 
catch NPE when popup bubble for unread mentions is not available anymore
> catch NPE for popup bubble

- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
After the Android sharing functionality was used, the shared text sticks
in the message composing field in the conversation. Also if an text was
forwared to the same conversation the text which was shared before
sticks in the message composing field.
Now the message composing field is empty after sharing or forwarding
something.
> Clear message field after sharing

- app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
this is a dirty workaround for issue #1677
Somehow onUserLeaveHint is executed when the user starts a videocall. If PIP is disabled, the logic inside enterPipMode would finish the activity right after it was started.
This workaround suppresses the execution of enterPipMode right after the activity was started.
However if a user would press the home button in the first three seconds, the call would continue in background without the ability to recover the UI.
To better fix this bug it must be found out why onUserLeaveHint is executed on start (this should not happen!).
> add workaround to start videocalls when PIP is disabled

- .github/workflows/qa.yml
Copied solution from the Nextcloud Files for Android app from commit
6863a8 [1].
From Álvaro's commit message:
> There is no way to skip the whole workflow depending on whether it is
> a PR from a fork or not. The only workaround is to check whether secrets are present or not.
>
> So, I've added a step to check if KS_PASS is empty, and set an output depending on that.
> If it is empty, we just skip the rest of the steps.
[1] https://github.com/nextcloud/android/commit/6863a8a637d4a02dd7a2a908e75d3b7b6f7901e2
> Skip QA build if keystore not available

- .drone.yml
- scripts/analysis/findbugs-up.rb
- scripts/analysis/lint-up.rb
With the parameter '--console=plain' Gradle produces a plain text log without
charachter garbage which is created by animations.
> Gradle should log plain

- app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/res/drawable/ic_check_black_24dp.xml
The check icon for selection in the contact listwas inverted.
Now correct orientation (✅) is used in LTR and RTL.
> Don't mirror check icon in RTL

- app/src/main/res/drawable/ic_mimetype_folder.xml
- app/src/main/res/layout/rv_item_browser_file.xml
* replace folder icon with files-client/material one
* align icon size and whitespace with files-client/material ones
* made checkbox a 48x48dp hitbox for improved accessibility (48dp is the min size according to Google's accessibility guidelines for clickable elements)
labelled for back-porting so the upcoming release is even further aligned UI/experience-wise between the clients 
> Align file browser layout and folder icon with files client

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
The background color for the indirect unread mention counter was alwasys
white. Also in dark mode.
Now the background color is defined via the 'bg_default' color.
> Fix unread indirect mention bg color

- app/src/gplay/java/com/nextcloud/talk/services/firebase/MagicFirebaseMessagingService.kt
- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
- app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.java
- app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
- app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
- app/src/main/res/layout/controller_settings.xml
- app/src/main/res/values/strings.xml
Trying to fix #756 and #892
This seems to be caused by the fact that since Android 8 (Oreo) notification sounds are handled by the system - as described in this article: [Create and Manage Notification Channels](https://developer.android.com/training/notify-user/channels).
Changes to implement - most should apply only to devices running Android 8 (Oreo) or later:
Addtional notes:
* I have refactored sound selection code to cover differences between old (pre Oreo) and new devices.
* I have changed the notification channel handling code to always use the same notification channel for calls. Previous implementation used a hash of the notification parameters as a channel ID. This prevented users from configuring call notification settings in the system UI.
Plus some refactoring - move more …
> Adapt notification code to Android 8.0 (Oreo) and later

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
- app/src/main/res/layout/view_message_input.xml
Should resolve #411
Added support for images received from keyboard as described here:
https://developer.android.com/guide/topics/text/image-keyboard
When a keyboard (like Google Keyboard) sends an image - usually a GIF 😜 - to the text entry field, the code uploads the image to the current chat.
Implementation is a bit tricky, since it "injects" a new class _ImageEmojiEditText_ into a part of the layout managed by external **ChatKit** component. However since the _ImageEmojiEditText_ inherits from _EmojiEditText_ used originally, **ChatKit** seems to work just fine. And we can attach the required callback in the _ChatController_ class.
> Image keyboard support in chat

- app/src/main/java/com/nextcloud/talk/controllers/RingtoneSelectionController.java
- app/src/main/java/com/nextcloud/talk/controllers/SettingsController.java
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
- app/src/main/java/com/nextcloud/talk/receivers/PackageReplacedReceiver.kt
- app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
Additions to PR #1728
**1. Remove unused notification channels during upgrade**
I have not correctly considered app upgrade. There were the following unintended side-effects when upgrading:
- the old "Calls notification channel" was still visible in the system UI but not used,
- the channel "Message notification channel" was not renamed to "Messages" as expected (registering the channel again with the same ID but a new name does not change the name of the channel).
The new code:
- removes all unused notification channels,
- uses a new ID (NOTIFICATION_CHANNEL_MESSAGES_V4) for the "Messages" channel.
**2. App would crash on pre-Oreo devices with "No sound" setting**
Null ringtone Uri must be allowed.
> Additional fixes related to notification channels

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
@mahibi follow-up to hide the "mark as unread" for now on releases but show on debug builds to be able to easily work on it in the future when time permits
> only show mark as unread in debug mode

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
Workaround for #1869
I have not figured out why avatarSize becomes <= 0 in this case. With this workaround the app seems to behave OK - I have not even been able to notice that the avatar is incorrect.
> Workaround for crash when loading avatar

- app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/ConductorRemapping.kt
- detekt.yml
Fixes #1861 
When **remapChatController** is called from a notification use a **SimpleSwapChangeHandler** rather than **HorizontalChangeHandler** to avoid animation.
This has the following effects:
- **ConversationsListController.onAttach** is not called in most cases (_occasionally when the **MainActivity** is destroyed and recreated the ConversationsListController.onAttach can still be called, but this seems rare_).
- The toolbar rather than the search bar is shown as expected.
- The **getRooms** API is **not** called.
- Screen flickering is significantly reduced. Sometimes the conversation list still becomes briefly visible, but in many cases the app shows the chat view immediately.
> Conversation view shows search bar when opened from notification

- app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
__Many thanks to @danxuliu and @Ivansss to figure this out!__
After the migration from WebRTC from plan b to unified plan in commit https://github.com/nextcloud/talk-android/commit/86f20dcfd37b9f510474e576ea8bc4d4df05f0d8
the media constraints are ignored for creating an answer on a peer
connection:
> Offer to Receive Options/Constraints
>
> These constraints are passed to PeerConnection’s methods for creating SDP to
> add placeholder media sections in case a sending track would not have already
> created one.
>
> With Unified Plan semantics, these are still supported for creating offers
> using a backwards compatibility shim (basically creating an RtpTransceiver if
> one doesn’t exist). It is recommended to switch to the RtpTransceiver API
> (example below). _They are no longer supported …
>  Use Transceivers instead of constraints to discard received video tracks 

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Fixes #1889
[When a new participant joins a call](https://github.com/nextcloud/talk-android/blob/1b30a6ef62dde17b9eb95a6867d03089a5b3dea9/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L1773) the Android app creates a connection with that participant. However, a connection with another participant was also created [when any signaling message was received from that participant and no connection existed yet](https://github.com/nextcloud/talk-android/blob/1b30a6ef62dde17b9eb95a6867d03089a5b3dea9/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L1547-L1548). In some cases a signaling message can be received from another participant before that participant has joined the call, so this caused a connection to be tried to be established with that participant. …
> Fix trying to establish a connection before a participant joins the call

- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
first try to fix #1914 
---
The toggleEmojiPopup method is a hacky workaround to avoid bug #1914
As the bug happens only for the very first time when the popup is opened,
it is closed after some milliseconds and opened again.
200 milliseconds seems to be a good value to initialize the popup correctly with the desired size
downside: there is even some flickering when opening the "more emojis" window
> add workaround to avoid emoji picker to take the full screen height

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
[The call flags describe the streams provided by the client](https://github.com/nextcloud/spreed/blob/5278e716c7e45c0751257cc0b14db1fbe344f40b/docs/constants.md#participant-in-call-flag), so in a video call both audio and video are provided, not just video.
Note that as publishing permissions are currently not implemented in the Android app the provided flags do not take into account the available permissions. Nevertheless, [the server restricts the flags based on the permissions](https://github.com/nextcloud/spreed/blob/c07251f0c67d3c02debe1f6dbe0e12ee3fe9f99a/lib/Service/ParticipantService.php#L1003-L1009), so the other participants would see the appropriate flags. In the future it would be better to send the right flags directly from the Android app.
Similarly, for now, it is just …
> Fix call flags in video calls

- app/src/main/java/com/nextcloud/talk/adapters/SharedItemsListAdapter.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/jobs/DownloadFileToCacheWorker.kt
- app/src/main/java/com/nextcloud/talk/repositories/SharedItem.kt
- app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
- app/src/main/java/com/nextcloud/talk/viewmodels/SharedItemsViewModel.kt
fix NumberFormatException for files >2,14 GB (=limit that can be represented by Int)
please review in detail as it will be a last minute fix for 14.0
> fix NumberFormatException

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ServerSelectionController.kt
- app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
For async calls the view can be destroyed before the call is finished.
This PR resolves #1958, #1959 and #1960.
> Catch NPEs on view bindings

- app/src/main/java/com/nextcloud/talk/activities/TakePhotoActivity.java
Some devices have a digital video stabilization mode that uses a
smaller field of view within the full set of sensor data, and moves
the selected subset around like on rubber bands in order to reduce
shaking in video captures. Most devices default this mode to OFF,
but some, like Pixel 6 Pro, default this mode to ON, which causes
image and video captures to have a reduced field of view.
This change will have no effect on most devices, but will increase
field of view to full on those devices that do not by default.
Reference: https://issuetracker.google.com/issues/230013960
Signed-off-by: Adam Serbinski <adam@serbinski.com>
> TakePhotoActivity: Use full field of view

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
currentConversation could have been null when opening the ChatController from notification.
hasChatPermission is now only set in
getRoomInfo
> avoid NPE when initializing chat permission

- app/src/main/java/com/nextcloud/talk/receivers/DirectReplyReceiver.kt
- app/src/main/res/values/strings.xml
Follow-up to #1923.
I have implemented a very basic notification when the reply cannot be sent. This is how it looks like at the moment.
The way this works and looks should probably be aligned with #1259.
Any suggestions?
> Reply from notification - initial error handling

- build.gradle
- Put jitpack and jcenter at the end of the repos list
- This should make it so dependencies are fetched from google and maven central first, which are faster and more stable
- remove jcenter, use gradle plugin portal as mirror where needed
- At the moment when this PR is opened, jcenter is not resolving properly, but gradle plugin portal is.
- This is NOT a permanent solution. We should upgrade or remove jcenter dependencies, see #2064 
- Some additional cleanup
> build: Fix/optimize gradle repo configuration

- .drone.yml
> Use 'emulator' instead of 'emulator-headless'

- app/build.gradle
Not longer needed since we're on Java 11.
> Remove kotlin option jvmTarget = "1.8"

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
In case anything goes wront during calling
'NotificationManger#activeNotification' an 'RuntimeException' will be
thrown. This results in a crash if not catched.
Resolves: #2078
> Catch RuntimeException thrown by NotificationManager

- app/build.gradle
- app/src/main/res/values/strings.xml
Removes the in commit cedd929f10 added string attribute 'tools:ignore'. These
would require an adjustment to our CI which we want to avoid.
So instead the lint check 'PrivateResousce' is globally deactivated.
See: commit cedd929f10, #2110
> Disable lint check 'PrivateResource'

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
While looking at #2122 I found that the logic for scrolling to unread messages was already present,
but was broken because of the condition changed in this PR.
Unfortunately I can't understand the reason for that condition, as the history has been lost and there's no explanation in the code. During testing, I didn't find anything broken
Perhaps one of the reviewers can give input?
Fixes #2122
> ChatController: fix scroll to unread messages

- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
Fix #2111 
My bad :disappointed:
This has been broken by my commit: [This setAction call seems strange and redundant](https://github.com/nextcloud/talk-android/pull/1923/commits/4bb4d6870a5f1b79f232f054d138fc3fdcc4a674).
At least I start to understand why this was necessary. :wink:
Here is an explanation regarding [creating a PendingIntent object](https://developer.android.com/reference/android/app/PendingIntent):
> Because of this behavior, it is important to know when two Intents are considered to be the same for purposes of retrieving a PendingIntent. A common mistake people make is to create multiple PendingIntent objects with Intents that only vary in their "extra" contents, expecting to get a different PendingIntent each time. This does not happen. The parts of the Intent that are …
> Use unique request code to create PendingIntent

- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
- app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
fix #2123
when the user status app on server is restricted to only some groups, the capabilities for users that are excluded still contains the "user_status" capability.
For the android talk app, this caused that the conversations were not shown.
With this fix, the conversations will be loaded also if the "user_status" is mistakenly set. Additionally, the option to set the status will be hidden.
to test, restrict the user status to some group and test with some user who is not included in this group
> fix to load conversation list (restricted user status)

- app/src/main/java/com/nextcloud/talk/controllers/base/NewBaseController.kt
These do not need to be nullable as they will be injected immediately. This will make child controllers code much cleaner.
I've chosen not to fix the now unneeded `!!` and `??` in all the child controllers as it would be too big a diff and could easily cause conflicts.
Instead, I suggest we clean those up as we work on Controllers in the future.
> NewBaseController: Inject kotlin fields without @JvmField and nullable type

- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ProfileController.kt
- app/src/main/java/com/nextcloud/talk/dagger/modules/UtilsModule.kt
- app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
- app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
- app/src/main/res/layout/controller_profile.xml
- app/src/main/res/values/strings.xml
> Upload profile picture from camera

- app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
fix https://github.com/nextcloud/talk-android/issues/2197
> catch NPE for binding (loadCurrentStatus#onError)

- app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
- app/src/main/java/com/nextcloud/talk/controllers/base/NewBaseController.kt
This is really a symptom of unreliable design around the async logic in Controllers. The data async calls should have been separate from the controller, so that the only asynchronicity the Controller has to deal with is UI-related, and can be cancelled safely on destroyView.
I have replaced the try/catches in ContactsController as a PoC
In the future as those controllers are converted to something that has a separate ViewModel, this kind of catch should be completely unneeded.
> Add method in NewBaseController to handle NPE catches for viewbinding

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
This fixes a bug which is described in #2181
Be aware that #2181 is not completely fixed with this because there are still scenarios that can cause the bug. The issue will remain open..
This reverts a change from a24f49c7
Before a24f49c7 in onDestroy() the disposables were not disposed. Instead this was "only" done in onComplete() of leaveRoom().
See a24f49c#diff-6b47d0e9875a7f7d5c1e6b80feab998e92d29b0cda8ac9bbf427aab99e56d209R1827
Because with a24f49c7 was now executed in onDestroy() , the leaveRoom() method is not executed successfully because it's destroyed too early. This results in multiple calls of getRoomInfo() with different roomTokens.
> fix switching conversation titles

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
Status was not hidden on group/chats without status, thus old status was shown.
(I am unsure if changed hashCode is needed, but FlexibleAdapter checks in some way if item has changed and thus to be sure that a changed status will result in an updated view, I added it.)
> Fix status visibility in conversation list

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.java
follow-up for #2267 since status can be null hence running into a NPE which kills the "unread notification" popup bubble.
> Make equals null-safe in case no status is set

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
- app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
- app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsAdapter.kt
- app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsListViewHolder.kt
- app/src/main/java/com/nextcloud/talk/shareditems/adapters/SharedItemsViewHolder.kt
- app/src/main/java/com/nextcloud/talk/shareditems/model/SharedFileItem.kt
- app/src/main/java/com/nextcloud/talk/shareditems/model/SharedItem.kt
- app/src/main/java/com/nextcloud/talk/shareditems/model/SharedItems.kt
- app/src/main/java/com/nextcloud/talk/shareditems/model/SharedLocationItem.kt
- app/src/main/java/com/nextcloud/talk/shareditems/model/SharedOtherItem.kt
- app/src/main/java/com/nextcloud/talk/shareditems/model/SharedPollItem.kt
- app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepository.kt
- app/src/main/java/com/nextcloud/talk/shareditems/repositories/SharedItemsRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/shareditems/viewmodels/SharedItemsViewModel.kt
- app/src/main/res/layout/shared_item_list.xml
- app/src/main/res/values/strings.xml
Add missing types in the shared items view
<table>
<tr>
<th>
</th>
<th>
</th>
</tr>
</table>
Resolves #2029
> Shared items: Add tabs for polls, deck cards, locations and other objects

- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.java
Instead of a 64px avatar now the 512px version is loaded for
conversation lists. For avatars in a single conversation that was
already the case.
Resolves: #2302
> Load higher resoliton avatars in conversation list

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ConversationInfoController.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
- app/src/main/java/com/nextcloud/talk/models/json/converters/EnumSystemMessageTypeConverter.kt
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
- app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
- app/src/main/res/layout/controller_conversation_info.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
resolve #2281
Conversation settings | Conversation settings dark | Expiring messages dialog 
------- | ------- |-------- 
Tasks:
Follow-up possible:
- Off
- 4 weeks
- 1 week
- 1 day
- 8 hours
- 1 hour
- Handling of expiring messages must be implemented in a cleaner way once offline support is done with the new architecture. (right now data is modified on the adapter itself which is not a good practice).
- Setting time for expiring messages must be implemented in a cleaner way once dependency `com.yarolegovich:mp` is replaced with plain android solutions.
> handle expiring messages

- app/src/gplay/java/com/nextcloud/talk/services/firebase/ChatAndCallMessagingService.kt
- app/src/main/java/com/nextcloud/talk/controllers/SettingsController.kt
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
new notification channels must not be deleted. for this an enum was created, so that in removeOldNotificationChannels there is no manual work to do
> fix to keep notification channels

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Fixes #2347, which is a regression introduced in https://github.com/nextcloud/talk-android/pull/2326/commits/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44
`endPeerConnection()` removes the item from the list, so neither a for-each loop nor an iterator can be used to traverse the list; otherwise a `ConcurrentModificationException` is thrown due to modifying the collection while iterating over it.
In the past this was done using a good old for loop, but that could potentially skip some items too, as removing an item could move the rest of the items towards the head, while the iterator count was advanced towards the tail.
To solve that now the list of connections is first traversed to get all the sessions, and then the list of sessions is traversed to end the connections.
> Fix crash after hangup due to modifying a list while iterating over it

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Fixes (the part about a duplicated set of join/leave messages) #2060
When a publisher failed or starting the call timed out the call activity was closed instead of kept open. This was caused by handling all disconnected call flags for the current participant as being triggered by a moderator ending the call (a regression introduced in https://github.com/nextcloud/talk-android/commit/f70f94e6be18c07e64bdb1b6491b48407c98bee1). Now the state of the Android app is also taken into account when processing those messages, and only when the local participant left the call due to a remote action the call activity is closed.
Independently of that, when the HPB is used the call is joined and left again when the call activity is closed and the chat controller is opened. When [the chat controller is …
> Fix issues when leaving calls

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
When a publisher fails during a call a [reconnection is triggered](https://github.com/nextcloud/talk-android/blob/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L2090-L2095), which [first leaves the call](https://github.com/nextcloud/talk-android/blob/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L1730) and then [initiates it again](https://github.com/nextcloud/talk-android/blob/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L1743-L1746). Initiating a video call first [request the permissions](https://github.com/nextcloud/talk-android/blob/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44/app/src/main/java/com/nextcloud/ …
> Fix call not joined again if reconnecting while in PiP mode

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/res/layout/call_activity.xml
- app/src/main/res/values/dimens.xml
The self video had a _wrap_content_ height when coming back from PiP mode, which caused it to expand and occupy the full window height. Now the height is set to the same value used when starting the call activity.
As this is just a quick fix no fancy things like basing the self video size on the screen size and ratio were added :-)
- Start a video call
- Go back to the chat without leaving the call (for example, pressing the back button)
- Tap on the PiP window to maximize the call activity again
The self video view has the same size as when the activity was first launched
The self video view occupies the full window height (it can be noticed by the position of the button to switch the camera, as it is aligned to the bottom)
> Fix self video size after coming back from pip mode

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
The chat controller [gets the room information again and again to check whether the lobby is enabled](https://github.com/nextcloud/talk-android/blob/5a2b04740b0123e42670defb85535a5843630b7e/app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt#L383-L392) and update the UI as needed. This [loop is stopped](https://github.com/nextcloud/talk-android/blob/5a2b04740b0123e42670defb85535a5843630b7e/app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt#L1994-L1998) when the chat controller is detached, but only [if no call is active](https://github.com/nextcloud/talk-android/blob/5a2b04740b0123e42670defb85535a5843630b7e/app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt#L1825); if a call is active the room information will still be got again and again, …
> Fix checking lobby state from chat controller while in a call

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
[The local stream is set](https://github.com/nextcloud/talk-android/blob/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L451) only when [the activity is created](https://github.com/nextcloud/talk-android/blob/f10d74f0ed34a37a9f6f58ec09686068a7dc1d44/app/src/main/java/com/nextcloud/talk/activities/CallActivity.java#L338). However, it was disposed when hanging up, which happens not only when closing the activity, but also in cases in which the call activity is kept open and the participant reconnects to the call (for example, when starting the call times out), which caused the local stream to freeze. Now the local stream is disposed only when the call activity is destroyed.
The test below requires the fixes for leaving the call …
> Fix disposing local stream when the call activity is not being left

- app/src/main/res/layout/call_states.xml
The call state uses a RelativeLayout with a wrap content height where the state icons (including the progress bar) position was set as above the message. However, this caused the call state to wrap only the text; the icons were indeed above the message, but out of the view boundaries.
Now the icons are wrapped in a FrameLayout and the text position is set below that frame layout instead, which causes the RelativeLayout height to correctly wrap its content.
The last part (checking the time out icon) of the test below requires the fixes for leaving the call (#2387 and #2388), as otherwise the call activity is closed rather than kept open when timing out.
- Start a call (and do not join it from any other device)
The progress bar is shown above the message; after 45 seconds the timer icon is …
> Fix icon not visible in call state message

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
When the HPB is used and the publisher fails (which is a disconnection that can not be automatically solved by itself) a forced reconnection is
triggered. This restarts the call, so some feedback should be provided in the UI about it.
The test below requires the fixes for leaving the call (#2387 and #2388), as otherwise the call activity is closed rather than reconnecting when the publisher fails.
- Setup the HPB, but do not enable a TURN server with TCP
- Block UDP connections from the Android device (so the publisher fails to connect to the HPB and triggers a reconnection)
- Start a call
- Wait until the publisher fails
The call is tried to be joined again and a _Reconnecting_ message is shown in the call state
The call is tried to be joined again, but no specific message about that is …
> Show message in call state when the publisher failed

- scripts/analysis/getBranchName.sh
The GitHub API response contains the base branch in which the changes should
pulled into. This is now extracted with 'jq' from the response.
Also some Shellcheck issues were fixed.
> Determine base branch with 'jq'

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
see https://github.com/nextcloud/spreed/pull/7959
> hide poll creation for 1:1 conversations

- app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
- app/src/qa/res/mipmap-anydpi-v26/ic_launcher.xml
In alignment with https://github.com/nextcloud/android/pull/10745
Resolves #2407
> Added monochrome icon for Android 13 "Themed icons" support.

- app/src/main/res/layout/dialog_poll_results.xml
- app/src/main/res/layout/dialog_poll_vote.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
fix https://github.com/nextcloud/talk-android/issues/2426
before (on small screens) | after
-------- | -------- 
> change poll buttons to vertical orientation

- app/src/main/java/com/nextcloud/talk/conversation/info/GuestAccessHelper.kt
Before this change after enabling and disabling the guest access option,
the option stays enabled.
Resolves: #2378
> Fix wrong guests access option status

- app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
fix https://github.com/nextcloud/talk-android/issues/2432
with https://github.com/nextcloud/talk-android/pull/2364 it was implemented to hide the reactionsEmojiWrapper when no emojis are set for a message. whenever a emoji was added, it was actually not shown because the wrapper was still hidden.
with the fix, the wrapper is made visible again
> fix to show reactionsEmojiWrapper

- app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.java
fix to respect permission when call if answered by notification
> set participantPermissions in CallNotificationActivity

- scripts/analysis/getBranchName.sh
Not the name of the branch were the changes should pulled into is
needed. The name of the current branch must be determined.
Resolves error introduced with cc1e1270e1daabb6b9700792debdecb22b072c77
```json
{
"url": "https://api.github.com/repos/nextcloud/talk-android/pulls/2393",
"id": 1059797651,
...
"head": {
"label": "nextcloud:fix-icon-not-visible-in-call-state-message",
"ref": "fix-icon-not-visible-in-call-state-message",
"sha": "7bb84fcf020bbde20f48e89f1542bcded0674453",
...
},
"base": {
"label": "nextcloud:master",
"ref": "master",
"sha": "61b343c73f3c5833ae0f3e42b6d12f40610a3702",
...
},
"comments": 3,
"review_comments": 0,
"maintainer_can_modify": false,
"commits": 1,
"additions": 28,
"deletions": 22,
"changed_files": 1
}
```
> Get branch name from head instead of base

- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
- app/src/main/res/drawable/ic_baseline_error_outline_24dp.xml
- app/src/main/res/values/strings.xml
Partially addresses https://github.com/nextcloud/talk-android/issues/2346, but only shows that an error happened and doesn't offer any options.
> Show error when loading chats fails

- app/src/main/AndroidManifest.xml
This then should allow us to install Talk on Chromebooks
> Like Android Files we should rely on generic camera feature, but not required.

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Follow up to #2390 (technically the regression was introduced by c3f1f6c, but it is caused by a previous existing bug computing the new sessions, #2390 only revealed that bug)
Labelled as `developing` until I can verify some claims regarding the HPB that I have made in a commit message :-P But it could be reviewed in the meantime (and even merged if needed if you can live with a commit description that might not be fully accurate ;-) ).
The new sessions are computed by substracting the old sessions (those for which a `PeerConnectionWrapper` exists) from the sessions currently in the call. However, when `oldSessions` was used for that it no longer contained the old sessions, it only contained the sessions which were no longer in the call. As those sessions are mutually exclusive with the …
> Fix computing new sessions in call

- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
This might fix #2519
These changes fixed the issue for me. I was inspired by this article on SO:
https://stackoverflow.com/a/65132840
Unfortunately I am not able to test it reasonably in the next few days.
@mahibi - feel free to reject this PR if you have a better solution.
> File upload always fails for 1MB+

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
The URL for the avatar depends on whether the call participant is a user or a guest and, if it is a guest, on its nick. Although the user id of a participant does not change if the participant is a guest the nick may be changed during a call, so the avatar URL needs to be updated as well.
As the avatar URL is fully derived from other properties it is now calculated internally in the ParticipantDisplayItem and calculated when any of the properties it depends on changes (also for the user id for completeness, as technically the item could be reused for a different participant with a different user id, even if it is not currently done).
The issue does not depend on whether the HPB is used or not.
- Start a call in the Android app
- In a browser, open the conversation as a guest
- Join the …
> Fix update of guest avatars in call participants

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
When the internal signaling server is used the observable to pull signaling messages is subscribed again after each completion, but in case of an error it was retried only 3 times. Those 3 times are not in a row, though, but in total for the whole observable, no matter how many times it was subscribed again.
Due to the limitation on retries in a long call with a flaky connection pulling the signaling messages could fail more than 3 times, which caused the observable to finish with an error and therefore stop further pullings. In this situation the Android app would not notice if other participants joined or left the call, and thus it would not establish a connection with them or stop it.
Now the number of retries is unlimited, but each new request is increasingly delayed (up to 16 …
> Keep retrying with exponential backoff if pulling signaling messages fails

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
ParticipantDisplayItems are not associated to a full participant but to each of the single connections that the participant may have (video and screen). However, when they are added to the map only the session ID is used as key. Due to this when a participant starts a screen share the ParticipantDisplayItem for the screen share overwrites the item for the video, and once the screen share is stopped the old item is not restored. Moreover, if a participant is already sharing a screen when the local participant joins whether the video or the screen share is shown is undefined and depends on which connection is established first.
To solve that the ParticipantDisplayItems are now associated with both the session ID and the video stream type ("video" or "screen"). Due to this both the video and …
> Fix remote participants display with both video and screen share

- app/src/main/res/values/strings.xml
see https://github.com/nextcloud/talk-android/issues/2418#issuecomment-1316570085
spreed usage can be restricted by admins to groups. For this case users should get a error message which also takes this into account. Else it could be frustrating for users to find out why talk  is not working.
> add more precise text when spreed is not available

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Follow up to #2390
It seemed to work (that is, the progress bar was shown or hidden on the local participant with HPB depending on whether the connection was working or not), but that was probably thanks to a String pool or other similar optimization done by the JVM :shrug:
> Fix String comparison using operator rather than "equals()"

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
Follow up to #2503
What was I thinking on...? :facepalm: Sorry for the mistake :-(
The `ParticipantDisplayItems` were associated to both the session ID and the video stream type ("video" or "screen"), but the code that gets them was not updated to include the video stream type in the key.
I have pushed the commits in this pull request also to the backport for #2503, that is, #2564
Besides the steps below there are several other ways to test it (changing the nick, enabling or disabling the audio, or having a temporary disconnection by the remote participant)
- Start a call with video in the WebUI
- Join the call from the Android app
- In the WebUI, disable the video
In the Android app the avatar is shown for the remote participant
In the Android app the video turns black (because the WebUI …
> Fix ParticipantDisplayItems not updated on events

- app/src/main/res/values/strings.xml
backport of #2574 
fixes  #2577
> [stable-15.0] add more precise text when spreed is not available

- app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
The call flags should be checked using bitwise operators; otherwise a call with phone (`in call | with phone` / `in call + with phone` , that is, `0001 | 1000 = 1001` or `1 + 8 = 9`) would be seen as a call with video (`in call | with video` / `in call + with video`, `0001 | 0100 = 0101` or `1 + 4 = 5`), as `9 >= 5`. On the other hand, using bitwise operators (and only checking against "with video") succeeds only when the call flags contain `with video` (in the previous example, `1001 and 0100 = 0000`, so it does not succeed).
The `IN_CALL` flag is no longer checked, as `WITH_VIDEO` will be set only during calls, and therefore checking for `IN_CALL` is not needed.
As far as I could see other checks in the code against the call flags are fine; I hope not to have missed any :-)
By the way, …
> Fix "isInCallWithVideo()" check

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
When the web socket is abruptly closed it is connected again and the call is rejoined. However, the call was rejoined in a background thread, so an exception was thrown when trying to modify the views, which prevented the call from being joined again.
Besides that the call state needs to be explicitly changed, as if the web socket was connected again while in a call the state would be already "JOINED" or "IN_CONVERSATION", which prevents the signaling settings from being fetched again after the permissions check, and therefore also prevented the call from being joined again.
- Setup the HPB
- Start a call in the WebUI
- Join the call in the Android app
- Kill the external signaling server and start it again (note that only the external signaling server should be killed; Janus should not, …
> Fix reconnection when the web socket was abruptly closed

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/LinkPreview.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
> avoid to set link preview content from wrong message/ make link preview messages able to be swiped left

- app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
The module class is not supposed to have things injected into it. @Provides-annotated methods
will have their parameters injected, instead.
Fixes #2638
> RepositoryModule: fix wrong injection for dateUtils

- app/src/main/java/com/nextcloud/talk/controllers/ContactsController.kt
> avoid NPE in processAutocompleteUserList

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
Fixes? #1316 (it is very similar to scenario 1, although not exactly the same, but that could be because other things changed in the code in the meantime)
When a call is joined the call flags of the local participant change, so this causes a signaling message to be sent by the server. When the HPB is used the signaling message is sent through a WebSocket, which is already connected before joining the call. Therefore, in some cases the signaling message can be received through the WebSocket even before the response to the HTTP `joinCall` request.
The call state was set to `JOINED` when the `joinCall` response was received, but this could override the `IN_CONVERSATION` state already set when processing the participant list sent through the WebSocket. Additionally as the call state may not …
> Fix joining call when signaling messages overtake the response

- scripts/analysis/analysis-wrapper.sh
See https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/
This will still let us see the summary even for third-party PRs where secrets are unavailable.
How it looks:https://github.com/nextcloud/android/actions/runs/3748919814
How to get to it: click "details" next to the analysis check, then click "summary" in the left bar
> Analysis: Also publish summary to GITHUB_STEP_SUMMARY

- app/build.gradle
> bump webrtc version to 108.5359.0

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
- app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItemNotifier.java
- app/src/main/java/com/nextcloud/talk/adapters/ParticipantsAdapter.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantListNotifier.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantModelNotifier.java
- app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
- app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
- app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java
- app/src/test/java/com/nextcloud/talk/call/CallParticipantListTest.java
Fixes #2544
~~Requires #2590 (so the first commit of this pull request is _Handle the raw ICE connection state in the views_)~~
It is highly recommended to review this commit by commit rather than all at once ;-) Commit messages may also provide additional context.
Model classes for call participants were added. `CallParticipant` is the main model class, which observes the changes in its peer connections and data channels and updates a data object that keeps track of the state*. This data object is the one exposed to the view classes through a read-only object (`CallParticipantModel`) that can be also observed for changes on specific threads. Thanks to that the `ParticipantDisplayItems` are now automatically updated in the main thread when the model changes, and they also propagate the …
> Split call participants and peer connections

- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
When the HPB is not used and a `PeerConnectionWrapper` is created it always sent an offer if the local session ID is higher than the remote session ID. However, in the case of screen shares the participant sharing the screen always sends an offer, no matter the session ID. Therefore, when that offer was received the new `PeerConnectionWrapper` object sent a new offer, which in turn created an extra connection in the browser.
Although the screen share connection happens to work the underlying behaviour was wrong, so now no offer is sent for received screen share connections and it is always waited until the offer is sent by the other participant.
- Do not setup the HPB
- Open a conversation in the Android app
- Open the same conversation in the browser
- Check if the session ID of the …
> Do not create offer for received screen share

- app/src/main/java/com/nextcloud/talk/activities/CallNotificationActivity.kt
this could happen very rarely when clicking very fast to accept the call before the conversation was set.
> avoid crash when answering call

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
> improve voice message quality

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/res/drawable/ic_baseline_keyboard_double_arrow_down_24.xml
- app/src/main/res/layout/controller_chat.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
fixes #2470 
- Scrolls to the bottom using `smoothScrollToPosition(0)` meaning that the scroll animation can be interrupted if wanted
- Scroll is based off percentage of layout scrolled, with 0.0 being at the top of the chat, and 100.0 being at the bottom. I know that's a little weird, so I left a comment there. 
- I just set the `ImageButton` to only appear at anything past 90, and to be invisible by default.
🌙 Dark | ☀️ Light
---|---
[issue-2470-test-webm-smaller.webm](https://user-images.githubusercontent.com/69230048/215351025-5b2249de-1a6e-4a09-a3a3-471a0b8b8ceb.webm)
^^ Sorry about the blurry footage, just to be clear the button isn't animated it just disappears.
> Added A scroll down button + new icon + some styles for the button

- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
@mahibi discussed with @nickvergessen - we shall activate the feature for everybody even though it won't always work (hidden in case the code couldn't determin the `id` of the previous message (needed for the unread marker)
> Activate mark-as-unread on message level for everyone

- app/src/main/java/com/nextcloud/talk/controllers/base/BaseController.kt
Before this fix, it was not possible to go to conversation list when a message was opened by notification
> Fix to show back button when message opened by notification

- app/build.gradle
sucessfully tested for audio + videocalls with and without hpb.
> bump webRtc lib to 110.5481.0

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
- app/src/main/java/com/nextcloud/talk/models/json/converters/EnumRoomTypeConverter.java
resolve #2719
technical debt: code in viewHolders is redundant. will be improved when working on chatKit..
> add support for FORMER_ONE_TO_ONE conversations

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
fixes #1090 
Implemented automatic scrolling to a quoted message on tap. 
[issue-1090-test-webm.webm](https://user-images.githubusercontent.com/69230048/221612508-f54713d0-262c-40cf-b092-cc4281248b44.webm)
> Implemented automatic scrolling to quoted messages on tap

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
fix #2060
fix  #2171
might fix #2372 (can't reproduce right now, also not without this PR)
Please test/review carefully
1. Join chat on android
2. Rotate device with screen being allowed to rotate
3. Send message to android
message shown twice
message shown once
1. Join chat on android
2. Join call for this room on android
3. Leave call on android
4. Send message to android
message shown twice
message shown once
> Avoid duplicated messages / Fix messages not being displayed

- app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
- app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
- app/src/main/res/layout/dialog_set_status.xml
fix #2817
🏚️ Before | 🏡 After (themed)
---|---
> Fix theming of set status dialog buttons

- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
> Avoid NPE for voice message recording

- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
follow up to https://github.com/nextcloud/talk-android/pull/2802
> Scroll to quoted message also for outgoing messages

- app/src/main/res/layout/call_activity.xml
Without this fix, the call buttons became huge in landscape mode.
The LinearLayout of the callControls now has a fixed width which comes in handy in landscape mode.
---|---
> Fix horizontal (=landscape) call design

- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
- app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/jobs/CapabilitiesWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/SignalingSettingsWorker.java
- app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
This PR fixes to set the externalSignalingServer to the user, see 8c991c697fcbdef8e075cefa8c8026b6dbee2a8a
Furthermore, race conditions of Workers are now avoided by using WorkManager chains, see 609e5a2c7113cb7847104122d35dbd7eaca26f7e
> Fix to get websocketInstance

- app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
- app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFilesystemOperation.java
- app/src/main/java/com/nextcloud/talk/components/filebrowser/webdav/ReadFolderListingOperation.kt
- app/src/main/java/com/nextcloud/talk/controllers/WebViewLoginController.kt
- app/src/main/java/com/nextcloud/talk/dagger/modules/RestModule.java
- app/src/main/java/com/nextcloud/talk/events/CertificateEvent.java
- app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
- app/src/main/java/com/nextcloud/talk/utils/ssl/KeyManager.java
- app/src/main/java/com/nextcloud/talk/utils/ssl/MagicTrustManager.java
- app/src/main/java/com/nextcloud/talk/utils/ssl/TrustManager.java
- app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
fix #2856
Before this change the initinalization of the trusted key store was
combined in one try-catch-block. If anything went wrong an new in memory
trusted key store was created. Programming against an exception is an
bad pattern.
So the initialization is now splitted into multiple try-catch-blocks
with it's own scopes and the decision if the trusted key store is newly
created in memory or loaded from a exisitng file is done by an if
condition check.
>  Split different exception scopes / Use own OkHttp client for coil

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
> Fix to display chips with emojis

- app/src/main/res/layout/call_activity.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
Alternative to #2848
* ensures buttons are always 48dp (for accessibility reasons
* wraps the buttons into more lines if they don't fit in one line
* places the raise-hand button according to the "button bar" of the call buttons
> Fix horizontal (=landscape) call design button layouting/sizing

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtil.kt
- app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
- app/src/main/res/values/strings.xml
> Bump target and compile SDK to 33

- app/build.gradle
See https://github.com/nextcloud/notes-android/pull/1720
---|---
B | A
> buildToolsVersion does not need to be specified

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
- app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/res/layout/activity_settings.xml
this PR replaces controllers with Activities, see https://github.com/nextcloud/talk-android/issues/1551
TODO or for follow up PR's:
- For now RingtoneSelectionController is not used (only important for Build.VERSION.SDK_INT < Build.VERSION_CODES.O)
- Reauthorize account is **temporarily** removed
- better solutions for account removal?
> Replace Controller with Activity for settings

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/nextcloud/talk/activities/MainActivity.kt
- app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
- app/src/main/java/com/nextcloud/talk/controllers/ChatController.kt
- app/src/main/java/com/nextcloud/talk/controllers/ConversationsListController.kt
- app/src/main/java/com/nextcloud/talk/conversation/info/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/conversation/info/GuestAccessHelper.kt
- app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
- app/src/main/res/layout/controller_contacts_rv.xml
- app/src/main/res/layout/controller_conversation_info.xml
this PR replaces controllers with Activities, see https://github.com/nextcloud/talk-android/issues/1551
Temporarily chats are opened via MainActivity and ConductorRemapping until chat is not an Activity.
> Replace Controller with Activity for conversationInfo and contacts

- app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
* Server issue: https://github.com/nextcloud/spreed/issues/6339
* Server PR: https://github.com/nextcloud/spreed/pull/6340
Resolves #2860 
Suggestion items | Mention chip in edit field | Mention chip in outgoing message
---|---|---
Some details:
* They are returned on the mentions endpoint, identify by `source=groups` and should be shown with label and group icon in the dropdown list
* They are like normal user and `@all` mentions just rich object parameters, this time with type `user-group`. We display them like all other mentions as a chip with a group icon as "avatar" (2 persons)
> Group mentions

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Fix to open conversation list when navigating back after chat was opened by notification
fix #2959 which was when working on https://github.com/nextcloud/talk-android/issues/1551
created https://github.com/nextcloud/talk-android/issues/2961 to migrate away from onBackPressed
> Fix to open conversation list when navigating back 

- app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
- app/src/main/java/com/nextcloud/talk/models/json/capabilities/SpreedCapability.kt
- app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
fix #2962
Because of "supported-reactions" and "predefined-backgrounds" the capabilities cannot be parsed with 
`var config: HashMap<String, HashMap<String, String>>?`
This is now
`var config: HashMap<String, HashMap<String, @RawValue @Contextual Any>>?` while always checking for the type when accessing the values.
```
"config": {
"attachments": {
"allowed": true,
"folder": "/Talk"
},
"call": {
"enabled": true,
"breakout-rooms": true,
"recording": true,
"supported-reactions": [
"❤️",
"🎉",
"👏",
"👍",
"👎",
"😂",
"🤩",
"🤔",
"😲",
"😥"
],
"predefined-backgrounds": [
"1.jpg",
"2.jpg",
"3.jpg",
"4.jpg",
"5.jpg",
"6.jpg"
],
"can-upload-background": true
},
"chat": {
```
"supported-reactions" and "predefined-backgrounds" are not handled yet.
> Handle new capabilities json structure

- app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
- app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
~~Parse value as String which should work for old values (Strings) and new Values (Boolean)~~
This PR fixes bugs that were introduced with https://github.com/nextcloud/talk-android/pull/2963/files
Basically replacing `as? String` (which would result in null) with `toString()`
> Fix call feature parsing

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantModelNotifier.java
- app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/models/json/signaling/NCMessagePayload.kt
- app/src/main/java/com/nextcloud/talk/signaling/CallParticipantMessageNotifier.java
- app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
- app/src/test/java/com/nextcloud/talk/call/CallParticipantModelTest.kt
- app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverCallParticipantTest.java
Besides the handling of received signaling messages for call reactions this pull request changes how the toast for raised hands is created. Although listening from the signaling was working fine and the new way unfortunately adds a "lot" of extra code it is conceptually "more correct", as the UI should not directly deal with the signaling if there is a higher abstraction available. Nevertheless, this change should ease adding support for other similar features, like displaying reactions.
> Handle received signaling messages for call reactions

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.java
- app/src/main/java/com/nextcloud/talk/call/ReactionAnimator.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MoreCallActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
- app/src/main/res/layout/call_activity.xml
- app/src/main/res/layout/dialog_more_call_actions.xml
resolve #2929
Reactions menu | Animated reaction
---|---
followup issue: https://github.com/nextcloud/talk-android/issues/2998
> Reactions in calls

- app/src/main/java/com/nextcloud/talk/translate/TranslateActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
Follow up on #3025 
Signed-off-by: Julius Linus <julius.linus@nextcloud.com>
Fixed the items not showing up and being clickable and the translate function being called upon orientation change,
https://github.com/nextcloud/talk-android/assets/69230048/b54a847c-6cd0-473b-b8a7-71d917bb7124
| 
https://github.com/nextcloud/talk-android/assets/69230048/699626d8-e16b-4ab8-be9d-88e86dceae92
> issue 2931 - follow up fixes

- app/src/main/java/com/nextcloud/talk/translate/TranslateActivity.kt
- app/src/main/res/layout-land/activity_translate.xml
- app/src/main/res/layout/activity_translate.xml
- app/src/main/res/values/strings.xml
...and fix layout issues for landscape mode while loading
on sermo (messages are faked!):
portrait|landscape
---|---
spinner positioning fixed (IDE layouting mode):
portrait|landscape
---|---
> Add copy to clipboard action for translations

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Signed-off-by: Julius Linus julius.linus@nextcloud.com
🏚️ Before
https://github.com/nextcloud/talk-android/assets/69230048/6cfa5daa-dba9-47c3-a06f-c461ef52ee79
🏡 After
https://github.com/nextcloud/talk-android/assets/69230048/1c7a7ce8-c478-4444-a318-e0dfd550db63
> Bug fix to filter conversations

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
- app/src/main/res/layout/item_custom_incoming_preview_message.xml
Fixes #2780 
Signed-off-by: Julius Linus julius.linus@nextcloud.com
---|---
> Authors Name is now above incoming previewed messages

- app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
Clicking on the mentioned filter used to only bring up mentions, direct or @all, now it also brings up all unread conversations that are 1:1 too, regardless if they contain a mention or not. 
Signed-off-by: Julius Linus julius.linus@nextcloud.com
🏚️ Before
https://github.com/nextcloud/talk-android/assets/69230048/9e7e0de7-c705-4d12-a79f-199663de7bed
🏡 After
https://github.com/nextcloud/talk-android/assets/69230048/8bfa057b-a69a-42b9-8571-ff432bfd611b
> WIP one-to-one behaves like mentioned

- app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
otherwise the list in the ConversationListActivity would handle it which results in unexpected user actions dialog popup
---|---
B | A
> fix long click in ChooseAccountDialogFragment

- app/src/main/java/com/nextcloud/talk/controllers/AccountVerificationController.kt
> fix to load conversationlist only once after login

- app/src/main/AndroidManifest.xml
this was temporarily disabled as a workaround because of https://github.com/nextcloud/talk-android/issues/3146 (So after screen rotation it could happen that chat was not updated.)
Now that the issue is solved, portrait mode will be allowed again
> allow screenOrientation for ChatActivity

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
fix #3162
could happen when using long click on header when using the conversation search
> avoid ClassCastException on ItemLongClick in ConversationsListActivity

- app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
> avoid NPE in ProfileActivity because userInfo could be null

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/dagger/modules/UtilsModule.kt
- app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
- build.gradle
Resolves #3154 
---|---
**Note** 
Items aren't interactive, so you can't tick of checkboxes ;)
> Implement text formatting via markdown

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/res/layout/item_custom_incoming_voice_message.xml
- app/src/main/res/layout/item_custom_outcoming_voice_message.xml
fixes #3142 
Instead of the 0:00/1:23 implementation that web has, I liked Telegrams implementation better, where they had a countdown instead. 
Also sorry about the huge diff in ChatActivity, my IDE automatically removed a bunch of redundant '?' operators. 😅 my actual diff is on line 1382 in ChatActivity
[issue-3142-before.webm](https://github.com/nextcloud/talk-android/assets/69230048/eaf39612-d198-4ed6-af3c-0e9cd13fc700)
[issue-3142-after.webm](https://github.com/nextcloud/talk-android/assets/69230048/e4d155c1-016b-4367-9071-6590f01a934d)
> Display total duration of voice messages

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- Also should fix the buggy seekBar
https://github.com/nextcloud/talk-android/assets/69230048/c53a8aa3-868d-4f75-a5dd-a476e0389434
[audio-duration-bug-after.webm](https://github.com/nextcloud/talk-android/assets/69230048/0a21c825-5c2f-415e-9710-9f24a759600c)
> Rewind & Replay bug fix for Audio Duration

- app/build.gradle
> Bump nextcloud.android-common:ui from 0.11.0 to 0.12.0

- app/src/main/AndroidManifest.xml
This fixes the problem where notifications (specifically, file upload progress) won't show for generic or qa build variants on Android 13.
Fixes https://github.com/nextcloud/talk-android/issues/3106
> Add manifest permission to post notifications

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/res/layout/activity_chat.xml
Resolves #2515
---|---
B | ![Screenshot_20230727_215841](https://github.com/nextcloud/talk-android/assets/1315170/2f55a146-bd85-4ea5-aeba-6f39b90aa596)
> Implement status infos on chat view for 1on1 conversations

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
...and fixing the reply ellipsizing for any reply messages
Resolves #3176
> Implement respecting the markdown rendering flag

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
- app/src/main/java/com/nextcloud/talk/utils/permissions/PlatformPermissionUtilImpl.kt
- app/src/main/java/com/nextcloud/talk/utils/singletons/ApplicationWideCurrentRoomHolder.java
- app/src/main/res/layout/call_activity.xml
- app/src/main/res/values/strings.xml
resolve #3175
Call screen with call time | Info when call is running since one hour (faked for 20s)
-------- | --------
> show call time and hint for one-hour calls

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/res/values/strings.xml
fixes #1918 
- Drafts are now saved in between rooms.
[issue-1918-draft-messages-2.webm](https://github.com/nextcloud/talk-android/assets/69230048/5321acc1-02aa-4472-9e02-2aa90d0bf725)
> Message drafts are now saved

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
- app/src/main/java/com/nextcloud/talk/utils/AudioUtils.kt
- app/src/main/res/layout/item_custom_incoming_voice_message.xml
- app/src/main/res/layout/item_custom_outcoming_voice_message.xml
Fixes [this](https://github.com/nextcloud/talk-android/pull/3202#issuecomment-1662220530)
- Larger Bar gap
- Centered time below play/pause button
- Time is the same color as the play/pause button
Unfortunately, I wasn't able to fix the play time size. It's puzzling as on paper they should be equal 
I believe that there is some underlying logic morphing the timestamp in `fun showReactions` located in the `com.nextcloud.talk.adapters.messages.Reaction`, but I didn't want to mess with it. 
---
I did some refactoring, so now the number of bars is calculated based off the width of the SeekBar itself. And by extension, the bar gap should also be calculated based off the width of the SeekBar, therefore no matter the size, it should always maintain a good ratio. …
> Follow up fixes for the Waveform SeekBar

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/adapters/items/AdvancedUserItem.java
- app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.java
- app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.java
- app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/Reaction.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/StatusDrawable.java
- app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
- app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.java
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
> Migration away from getScheme() calls

- app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
Introduced by #3235
* mention rendering
* checkboxes on dark theme
> Fix theming issues

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/GuestAccessHelper.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
fix #3267 as followup for #3210
> avoid file storage permission warning.

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
fixes #3265 
This wouldn't be a problem if Google added a state-change listener to MediaRecorder & MediaPlayer, but [apparently they have no intention of doing so.](https://issuetracker.google.com/issues/110763341) Maybe worth it to migrate to Exoplayer?
🏚️ Before
[issue-3265-before.webm](https://github.com/nextcloud/talk-android/assets/69230048/558a7d5e-91e5-44d4-a763-c7a413327546)
🏡 After
[issue-3265-after.webm](https://github.com/nextcloud/talk-android/assets/69230048/a4c7a3c8-e146-44e8-8ada-c65d5f34e93b)
> Fixed media recorder bug

- app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
Solves: #3270 
https://github.com/nextcloud/talk-android/assets/111801812/64f95423-ce92-4707-ba97-9b1d47efdff0
https://github.com/nextcloud/talk-android/assets/111801812/4c3c856d-59ae-4065-b31c-7b78ca61b18a
> Save media playback state

- app/src/main/AndroidManifest.xml
> fix warning: tag with empty body

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Fixes [this](https://github.com/nextcloud/talk-android/pull/3224#issuecomment-1686413712)
Small bug fix, when returning to a message draft the send button image is now shown instead of the voice record button.
[message-draft-bug-1-after.webm](https://github.com/nextcloud/talk-android/assets/69230048/132e9807-023e-4dd1-a078-a50df04874c0)
> Message draft bug fix

- app/src/main/res/drawable/ic_logo.xml
fix #2945
Decreased the icon size by 13 percent.
> decreased the Icon size in notification bar 

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
- app/src/main/java/com/nextcloud/talk/models/json/reminder/Reminder.kt
- app/src/main/java/com/nextcloud/talk/models/json/reminder/ReminderOCS.kt
- app/src/main/java/com/nextcloud/talk/models/json/reminder/ReminderOverall.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
- app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
- app/src/main/res/drawable/baseline_calendar_month_24.xml
- app/src/main/res/layout/dialog_date_time_picker.xml
- app/src/main/res/layout/dialog_message_actions.xml
- app/src/main/res/values/strings.xml
fixes #3221 
[issue-3221-draft-4.webm](https://github.com/nextcloud/talk-android/assets/69230048/62523660-05af-41b1-a85b-f2c9cc7b4a37)
> Notify Me Later About a Message

- app/build.gradle
please be aware that Alpha versions for
17.20.* are meant to be 17.2.*
This is because of a typo that happened in 17.1
> bump version to 17.2.0 Alpha01

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/res/layout/item_system_message.xml
> Backport/3298/detect talking and send data channel message stable17.1

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/utils/UserIdUtils.kt
- app/src/test/java/com/nextcloud/talk/utils/UserIdUtilsTest.kt
fixes #3279 
**Added Unit Test For UserIdUtils**
> Added Unit Test For UserIdUtils

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
fixed bug with audio messages not sending after pausing in continuous voice recording mode. I must have forgotten to remove those two if statements, when fixing a previous bug.
[voice-recording-bug-fix.webm](https://github.com/nextcloud/talk-android/assets/69230048/b2e18e5f-3c93-4cd5-98bc-12864a02e677)
> Fixed bug with continuous voice recording

- app/src/androidTest/java/com/nextcloud/talk/utils/VibrationUtilsTest.kt
- app/src/main/java/com/nextcloud/talk/webrtc/DataChannelMessageNotifier.java
- app/src/test/java/com/nextcloud/talk/utils/BundleKeysTest.kt
- app/src/test/java/com/nextcloud/talk/utils/UriUtilsTest.kt
- app/src/test/java/com/nextcloud/talk/utils/UserIdUtilsTest.kt
- app/src/test/java/com/nextcloud/talk/webrtc/DataChannelMessageNotifierTest.kt
- app/src/test/java/com/nextcloud/talk/webrtc/GlobalsTest.kt
- app/src/test/java/com/nextcloud/talk/webrtc/PeerConnectionNotifierTest.kt
**Added Instrumentation Test For VibrationUtils and Unit Tests for other files mentioned below.**
> Added Instrumentation Test and Unit Tests

- app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
fixes #3326 
Google's default time format is 12hr, I switched it to the time format of the device itself, whether it be 12 or 24
🏚️ Before
[issue-3326-before.webm](https://github.com/nextcloud/talk-android/assets/69230048/82f2b1fe-1d72-49f8-8634-2d903ad7e4ba)
🏡 After
[issue-3326-after.webm](https://github.com/nextcloud/talk-android/assets/69230048/0d7b7dad-f777-4d86-a00d-23d6019d367f)
> TimePicker format matches locale of device

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
followup to #3329
Without this fix, the ChatActivity would be started again in FileViewerUtils. There was an endless loop between ChatActivity and FileViewerUtils because of the wrong context. Instead to open the browser, the app did nothing or freezed.
> fix endless loop when opening urls and files app is not installed.

- app/src/main/java/com/nextcloud/talk/jobs/ContactAddressBookWorker.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/res/values/strings.xml
> Error 429 "Too Many Requests" is now handled

- app/src/main/res/layout/activity_full_screen_text.xml
Needs testing, currently in train and no local docker 😇
> make text in preview selectable, so that user can copy it

- app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedMessageInterface.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/res/layout/call_started_message.xml
- app/src/main/res/values/strings.xml
fixes #3260 
| Dark | Light | Guest |
|--------|--------|--------|
| <img width="168" alt="image" src="https://github.com/nextcloud/talk-android/assets/69230048/2a713f89-aed4-45d5-be0c-553b72cedc5e">| <img width="167" alt="image" src="https://github.com/nextcloud/talk-android/assets/69230048/d018f3e3-98f8-4c3c-98b5-091abaa5d6d2">| <img width="160" alt="image" src="https://github.com/nextcloud/talk-android/assets/69230048/8e30b917-4034-4a11-96ee-5618e66943bb">| 
[show-accept-button-1.webm](https://github.com/nextcloud/talk-android/assets/69230048/f798634a-b69a-4d46-bffd-6004731632fe)
- Both join audio and video buttons
- Gets deleted if call ends, persists despite state or adapter changes
- Themed
> Show accept call button in chat

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPollMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
> Use primary color for quoted, own messages

- app/src/main/java/com/nextcloud/talk/adapters/messages/CallStartedViewHolder.kt
- app/src/main/res/layout/call_started_message.xml
Context on a OnePlus 9 Pro
Replicated in IDE
---|---
Note: the profile picture also didn't load in the image. I think by setting the request size to small, this changed, but I'll need to test it some more to be sure. For now I also set the default profile to the account_circle_48dp
> Bug fix for accept call message

- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
- fixes #3335 
Basically, replaced every "\n" with "\s\s\n" before processing. No idea why that works, but it does for some reason.
> Fixes newline characters not creating new lines

- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
I didn't remove a couple lines of code after removing ```MaterialPreferences``` a while back. Also cleaned up ```SettingsActivity``` a bit because it was annoying me 😐 
🏚️ Before 
[bug_fix_privacy_button_before.webm](https://github.com/nextcloud/talk-android/assets/69230048/bc790d9b-60f0-45d2-ba2f-e09e8a6a4a73)
🏡 After
[bug_fix_privacy_button_after.webm](https://github.com/nextcloud/talk-android/assets/69230048/57643c8d-385b-472a-a3c0-9e8ab6601d66)
> Small Bug fix - Privacy button in settings not working

- app/src/main/java/com/nextcloud/talk/activities/FullScreenImageActivity.kt
- app/src/main/java/com/nextcloud/talk/activities/FullScreenMediaActivity.kt
- app/src/main/res/layout/activity_full_screen_image.xml
- app/src/main/res/layout/activity_full_screen_media.xml
- app/src/main/res/values-v27/styles.xml
- app/src/main/res/values/styles.xml
Solves: #3372 
https://github.com/nextcloud/talk-android/assets/111801812/142258b1-1db8-4bea-8866-9ccf46974d45
https://github.com/nextcloud/talk-android/assets/111801812/b3919ac0-2261-4f24-a6e5-b3ff9eee077d
> Remove use of setSystemUiVisibility in previews #3372

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
- app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
> fix emoji size in markdown headlines

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/AudioUtils.kt
- (hopefully) fixes #3325 
Changed the code so that upon the time limit being exceeded, the result is set to null instead of being left at 0, which causes an infinite loop. I also documented the file heavily, because to be honest it's not very intuitive. In hindsight I should have done both of these from the start.
[issue-3341-voice-message-1.webm](https://github.com/nextcloud/talk-android/assets/69230048/5d47647a-1e3c-42c1-8340-f013d6078a89)
> Fixes not able to execute audio messages

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
and rename paramter to match super class in case of use of names parameters
> Bump room to 2.6.0 

- CHANGELOG.md
17.1.1 was skipped as it's not released on gplay, for reason see https://github.com/nextcloud/talk-android/pull/3397
> Add changelog infos for 17.1.0 and 17.1.2

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/automotive_app_desc.xml
This PR reverts https://github.com/nextcloud/talk-android/pull/3225
The reason for this is that somehow Google playstore doesn't accept the app anymore when Android Auto support is enabled. There were multiple emails exchanged with google, but there is no reason given that makes sense why the app is declined. Some vague hint was that is is related to Android Auto, and indeed removing Android Auto support finally solved that the app was accepted again.
One reason from Google was "We could not access the in-app content with the login credentials that you have provided". But the credentials are provided and working. So it doesn't make sense why/how this is related to Android Auto.
For now i give up to understand what's going wrong with the google playstore policy checks.
Further hints might …
> Revert Android Auto support

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/dagger/modules/DatabaseModule.java
- app/src/main/java/com/nextcloud/talk/remotefilebrowser/viewmodels/RemoteFileBrowserItemsViewModel.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
- app/src/main/res/values/strings.xml
> Migrating away from StoreBox to DataStore

- app/src/main/res/layout/activity_conversation_info.xml
- app/src/main/res/values/strings.xml
> Rename message expiration title

- app/src/main/java/com/nextcloud/talk/remotefilebrowser/viewmodels/RemoteFileBrowserItemsViewModel.kt
followup to https://github.com/nextcloud/talk-android/pull/3249
i guess better would be to avoid context in viewmodel: https://stackoverflow.com/a/69226093
> fix crash when trying to upload from nextcloud

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Resolves #2464
---|---
This pull request hides the “unread mention” bubble when the search is activated https://github.com/nextcloud/talk-android/issues/2464
This pull request uses the BehaviorSubject to monitor the activation state of the search mode. BehaviorSubject emits true (boolean value) when search mode is active and false (boolean value) when search mode is inactive. 
UI elements should subscribe to the BehaviorSubject and show or hide the “unread mention” bubble based on search mode activation state. If the BehaviorSubject emits true, the UI hides “unread mention” bubble, whereas when the BehaviorSubject emits false, the ”unread mention” bubble is shown.
> hide "unread mention" bubble in search mode

- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
fix #3407 
https://github.com/nextcloud/talk-android/assets/111801812/806ecd32-7264-457d-aeb5-ca5ca4d59e9b
https://github.com/nextcloud/talk-android/assets/111801812/e0b91688-bd59-4f3b-9d95-5df11a02e453
> Solve chat list disappears on configuration change

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
- app/src/main/java/com/nextcloud/talk/adapters/messages/PreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatMessage.kt
- app/src/main/java/com/nextcloud/talk/remotefilebrowser/activities/RemoteFileBrowserActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/FileAttachmentPreviewFragment.kt
- app/src/main/res/layout/dialog_file_attachment_preview.xml
- app/src/main/res/layout/item_custom_incoming_preview_message.xml
- app/src/main/res/layout/item_custom_outcoming_preview_message.xml
- app/src/main/res/values/strings.xml
> File Captions 🏷️ 

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/translate/repositories/TranslateRepository.kt
- app/src/main/java/com/nextcloud/talk/translate/repositories/TranslateRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/translate/repositories/model/Language.kt
- app/src/main/java/com/nextcloud/talk/translate/repositories/model/LanguagesData.kt
- app/src/main/java/com/nextcloud/talk/translate/repositories/model/LanguagesOCS.kt
- app/src/main/java/com/nextcloud/talk/translate/repositories/model/LanguagesOverall.kt
- app/src/main/java/com/nextcloud/talk/translate/ui/TranslateActivity.kt
- app/src/main/java/com/nextcloud/talk/translate/viewmodels/TranslateViewModel.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.java
- app/src/main/java/com/nextcloud/talk/utils/database/user/CapabilitiesUtilNew.kt
- app/src/main/res/values/strings.xml
- fixes #3347 
Adjusting the translation feature to use the new API [docs](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-translation-api.html#get-available-translation-options). 
[issue-3347-1.webm](https://github.com/nextcloud/talk-android/assets/69230048/7318994f-e1d1-4378-b807-81c1819d2636)
- Added 4 new model data classes
- Added the new API function to NcApi
- Implemented the changes in the Repository + ViewModel
- Implemented the changes in the Activity
- Added some helper functions to support impl
Signed-off-by: Julius Linus <julius.linus@nextcloud.com>
> Adjusting translation provider

- app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
it's not yet tested, but from my pov this should...
fix #3243
fix #3105
Not sure for which cases unregister for notifications might fail, maybe @nickvergessen knows best.
Further improvements for user deletions will come with https://github.com/nextcloud/talk-android/pull/3436
> Fix to delete user when unregister for notifications failed

- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
this should fix https://github.com/nextcloud/talk-android/issues/3456
> close Call notification when onError is triggered.

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingPreviewMessageViewHolder.java
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingPreviewMessageViewHolder.java
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/MicInputCloud.kt
- app/src/main/java/com/nextcloud/talk/ui/WaveformSeekBar.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
- fixes #3302 
I decided to also implement some additional Bug fixes and some refactoring, in addition to the IllegalStateException bug fix. Figured it would be better than multiple PR's.
- Fixes IllegalStateException
- Refactored code to be clearer and manage the [state ](https://developer.android.com/static/images/mediarecorder_state_diagram.gif)of the MediaRecorder object directly
- Saves state of voice recording upon life cycle changes like what telegram has
- Waveform is now saved to storage, so it isn't recreated every time the user exits the activity
- Clicking the expanded restart record button while preview is playing stops the preview
- File captions don't crash now, when the itemView is clicked
- Note to Self now allows messages expired or all messages to be deleted
> Bug Fix - IllegalStateException in stopAudioRecording + Polishes

- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
> translate "no proxy" in settings

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
> avoid error when declining recording consent

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
Preparation for sdk=34, as needed by the files app where this fix got implemented first
> Bump hwsecurity-fido from 2.4.5 to 4.1.0-patch2

- app/src/main/java/com/nextcloud/talk/utils/AudioUtils.kt
- possible fix to recently closed #3325 
Guarantees, that regardless of Codec State, the process will end at 3 seconds, sharp. Returning an Empty float array if not finished. This should make it compatible with slower devices. Also guarantees that the `MediaExtractor` is not null before queuing a new input buffer, which might stop some bugs that prevent the `MediaCodec.BUFFER_FLAG_END_OF_STREAM` flag from being set.
> AudioUtils bug fix for media playback

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Resolves #3538 
This pull request handles the back button of forward message.
> Handle forward message back button

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
Resolves #1487
This pull request adds the feature to share the text message to other apps.
> Share message text to other apps

- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
- app/src/main/res/drawable/ic_cancel_white_24dp.xml
Fix: #2374 
https://github.com/nextcloud/talk-android/assets/111801812/80029b82-07b3-43a0-9da9-c2ce8cd93c4a
- Folder which is created to upload chunks gets deleted.
- Due to deletion no chunks of the file are left on the server so if we try to upload the same file again it would start from beginning.
- Worker which does the uploading work is cancelled.
- Notification of uploading file is also cancelled.
> Cancel upload from notification

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/res/drawable/ic_edit_note_24.xml
- app/src/main/res/layout/dialog_message_actions.xml
- app/src/main/res/values/strings.xml
- fixes #3584 
- Note to self option should only appear if conversation is available
- Shows a pop up if message is sent successfully
- Added ic_edit_note_24_xml
- Implemented in MVVM for cleaner data flow
- Added the option to the XML
Poll messages don't have message actions attached anyway.
> Implementing Add to Notes in Message Actions 

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/fullscreenfile/FullScreenMediaActivity.kt
The player will handle the audio focus shifts. Basically It would:
- Pause the already playing media when this player is started.
- Or If some other media starts this player would pause itself.
This would avoid two media's playing at the same time.
https://github.com/nextcloud/talk-android/assets/111801812/da9d2fcc-f389-42d9-b075-95be6b8dadf8
https://github.com/nextcloud/talk-android/assets/111801812/978668e7-1082-40bd-9c00-33a29dbd2417
> When a headset is unplugged or a Bluetooth device disconnected, the audio stream automatically reroutes to the built-in speaker. If you listen to music at a high volume, this can be a noisy surprise.
> 
> Users usually expect apps that include a music player with onscreen playback controls to pause playback in this case. Other apps, like games that don't …
> Handle audio focus and becoming noisy

- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
Fix: #2373 
https://github.com/nextcloud/talk-android/assets/111801812/9b3ba71f-d376-4e4a-994d-4d79eece4d47
> Grouping upload notification

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
> avoid to send "speaking" data channel message when mic is muted

- app/src/gplay/AndroidManifest.xml
followup to https://github.com/nextcloud/talk-android/pull/3533
FOREGROUND_SERVICE_PHONE_CALL is removed because it is not necessary.
Seems it was introduced when moving to Android 14 because NCFirebaseMessagingService originally contained android:foregroundServiceType="phoneCall"
But this foregroundServiceType is not allowed/necessary for NCFirebaseMessagingService so it was removed, but it was forgotten to also remove FOREGROUND_SERVICE_PHONE_CALL permission.
This commit will remove FOREGROUND_SERVICE_PHONE_CALL permission so release process on gplay won't complain.
> remove FOREGROUND_SERVICE_PHONE_CALL

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
- app/src/main/java/com/nextcloud/talk/webrtc/MagicWebRTCUtils.java
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
- app/src/main/java/com/nextcloud/talk/webrtc/WebRTCUtils.java
This PR introduces changes as followup to https://github.com/nextcloud/talk-android/pull/3665
also see comment https://github.com/nextcloud-releases/talk-clients-webrtc/issues/8 for explanation how the build process   was fixed
> webRtc v121.6167.0 followup

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/NetworkChatRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
Makes `ChatActivity` in pure MVVM. This creates a solid foundation of infrastructure for federation and for any future offline support. TBH this has been on the books for some time now, but I suppose federation gave me an excuse to finally dedicate some time to implementing it.
Essentially does this
1. Exposes the entirely of `ChatActivity` as an interface in `ChatRepository` with state handled in the `ChatViewModel`. In this way, handling errors from the server, doing checks upon JSON response, and developing a offline-first app become simpler.
Related
- #3569 
- #3529
> Preparing for federation - Developing data layer for chats

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/FileAttachmentPreviewFragment.kt
- app/src/main/res/layout/dialog_file_attachment_preview.xml
Fixes: #3572
https://github.com/nextcloud/talk-android/assets/111801812/a4a59bb8-5548-43f0-8a0b-58b48f28349d
https://github.com/nextcloud/talk-android/assets/111801812/b0bf27d9-ac5e-4695-98fa-d2b25722ced3
> Fix: File Attachment Preview Dialog crashes ChatActivity

- app/src/main/java/com/nextcloud/talk/adapters/items/ParticipantItem.java
- app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/res/values/strings.xml
Resolves #3651
This PR renames strings from circles to teams.
> Renaming strings from circles to teams.

- app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
- app/src/main/res/layout/activity_contacts.xml
Fixes: #3691
https://github.com/nextcloud/talk-android/assets/111801812/708a61e3-66cc-400c-87f9-17b27479b445
https://github.com/nextcloud/talk-android/assets/111801812/af79ea6c-79b1-41b7-9d9e-906af62d2a97
PS: the list data is just place holder because I couldn't see any contacts/groups in my nextcloud instance :-). Please confirm it behaves correctly with actual data.
> Place shimmer on top of the view to avoid view jumping

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
- app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/ParticipantPermissions.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/preferencestorage/DatabaseStorageModule.java
due to bad wifi in train just a tiny PR that i could do without reliable internet:
followup to https://github.com/nextcloud/talk-android/pull/3663 to add all spreed capabilies to enum.
> add rest of SpreedFeatures to Enums

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/FilterConversationFragment.kt
- app/src/main/res/layout/dialog_date_time_picker.xml
Fixes: #3676
https://github.com/nextcloud/talk-android/assets/111801812/4a6b607e-d84d-48ab-8d3f-6a423904fd0e
https://github.com/nextcloud/talk-android/assets/111801812/f89c48e3-1b72-42e7-a19f-e5a47515b320
> Fix: Use of parameterized constructor with fragments

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
hide some features that are not available (yet) for federation.
> hide some features if federation is not available

- app/src/main/res/layout/activity_contacts.xml
followup to https://github.com/nextcloud/talk-android/pull/3692
---|---
> fix placement of contacts header items

- app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
This PR fixes the Recents screen.
> Fix Recents Screen

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
How to test:
pre-requirement:
There are open conversations
without this commit:
1. go to search screen
2. go back to conversation list -> all open conversations are listed below own conversations
with this commit:
1. go to search screen
2. go back to conversation list -> only own conversations are listed
> fix to hide open conversations after returning from search

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
Without this commit, the read status was broken as [X-Chat-Last-Common-Read](https://nextcloud-talk.readthedocs.io/en/latest/chat/#receive-chat-messages-of-a-conversation) was not used. It was removed by https://github.com/nextcloud/talk-android/pull/3630
As a result all messages were marked as unread after waiting for 30 seconds.
With this commit the X-Chat-Last-Common-Read is used again. Messages are marked as read again also after 30 seconds.
> use X-Chat-Last-Common-Read to fix read status

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
Resolves #3614.
If the "delete-messages-unlimited" capability is available, deleting messages without any time restriction is possible; otherwise, the time limit for deleting messages is six hours.
> Implemented delete-messages-unlimited feature

- app/src/main/res/drawable/ic_mimetype_application_pdf.xml
- app/src/main/res/drawable/ic_mimetype_image.xml
- app/src/main/res/drawable/ic_mimetype_text.xml
- app/src/main/res/drawable/ic_mimetype_video.xml
- app/src/main/res/drawable/ic_mimetype_x_office_document.xml
- app/src/main/res/drawable/ic_mimetype_x_office_presentation.xml
- app/src/main/res/drawable/ic_mimetype_x_office_spreadsheet.xml
Companion PR to https://github.com/nextcloud/android/issues/12687 also adding proper SPDX headers to the changed files
> Update mine type icons

- app/build.gradle
there seems to be something wrong that alpha workflow did not update the apps version. Thats why gplay complains with
"Google Api Error: forbidden: Cannot update a published APK. - Cannot update a published APK." because it always tries to upload 19.0.0 Alpha 02.
On nextcloud ftp server, it was most probably always overwritten as there is an up to date alpha2 version.
Seeting the version number to 19.0.0 Alpha 02 should make sure that an alpha 3 is built on next automation run.
The root cause that the version was/is not changed by the automation is still unclear.
> manually bump to 19.0.0 Alpha 02

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
As lastMessageId is not available for federatedRooms, the API on server side now allows the messageID to be optional. This is done by this commit: messageId is null when it's a federated room.
> fix to mark federated rooms as read

- app/src/main/res/layout/activity_conversations.xml
Resolves #3688.
This pull request resolves the issue of the conversation's top app bar experiencing flickering due to scrolling the conversations to the bottom.
This issue is caused by the material library update from 1.10.0 to 1.11.0.
> Remove flickering background on the app bar

- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/SetPhoneNumberDialogFragment.kt
- app/src/main/res/layout/dialog_set_phone_number.xml
- app/src/main/res/values/strings.xml
Fixes: #3737 
https://github.com/nextcloud/talk-android/assets/111801812/d2f59153-8402-49fd-9eab-94624a3f81c6
> Use DialogFragment for Phone Number Integration

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
- app/src/main/java/com/nextcloud/talk/lock/LockedActivity.kt
- app/src/main/java/com/nextcloud/talk/profile/ProfileActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/PickImage.kt
Resolves: #3742
Functionalities listed below uses new result APIs and working correctly
- **ChatActivity**
- **LockedActivity** 
- **Pick Image in both ProfileActivity & ConversationInfoEditActivity**
> Use new Result APIs instead of startActivityForResult() and onActivityResult().

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/res/layout/activity_chat.xml
Resolves #3765.
The edit message view is only shown when the user edits a message.
> shows edit message view only when user edits a message

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- fixes #3734 
[ConcurrentModificationException](https://developer.android.com/reference/java/util/ConcurrentModificationException)
>This exception may be thrown by methods that have detected concurrent modification of an object when such modification is not permissible.
>
>For example, it is not generally permissible for one thread to modify a Collection while another thread is iterating over it. In general, the results of the iteration are undefined under these circumstances. Some Iterator implementations (including those of all the general purpose collection implementations provided by the JRE) may choose to throw this exception if this behavior is detected. Iterators that do this are known as fail-fast iterators, as they fail quickly and cleanly, rather that risking arbitrary, …
> Fix crash on sendStopTypingMessage

- app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
> translate all boolean values in diagnosis screen

- app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
NPE without this fix (for 19.0.0 RC1):
```
Exception java.lang.RuntimeException:
at android.app.ActivityThread.performResumeActivity (ActivityThread.java:4975)
at android.app.ActivityThread.handleResumeActivity (ActivityThread.java:5008)
at android.app.servertransaction.ResumeActivityItem.execute (ResumeActivityItem.java:54)
at android.app.servertransaction.ActivityTransactionItem.execute (ActivityTransactionItem.java:45)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2386)
at android.os.Handler.dispatchMessage (Handler.java:106)
at android.os.Looper.loopOnce …
```
> avoid NPE when serverVersion is not known

- app/src/main/java/com/nextcloud/talk/conversation/CreateConversationDialogFragment.kt
NPE without this fix:
```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
at android.content.ComponentName.<init> (ComponentName.java:132)
at android.content.Intent.<init> (Intent.java:8269)
at com.nextcloud.talk.conversation.CreateConversationDialogFragment.initiateConversation (CreateConversationDialogFragment.kt:276)
at com.nextcloud.talk.conversation.CreateConversationDialogFragment.access$initiateConversation (CreateConversationDialogFragment.kt:63)
at com.nextcloud.talk.conversation.CreateConversationDialogFragment$addParticipants$1.invoke (CreateConversationDialogFragment.kt:257)
at com.nextcloud.talk.conversation.CreateConversationDialogFragment$addParticipants$1.invoke …
```
> avoid NPE when context is not known when creating conversation

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
- app/src/main/java/com/nextcloud/talk/models/domain/ConversationModel.kt
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
- app/src/main/java/com/nextcloud/talk/models/json/converters/EnumRoomTypeConverter.java
- app/src/main/java/com/nextcloud/talk/utils/ConversationUtils.kt
fix #3547
followup fix for https://github.com/nextcloud/talk-android/pull/3351/files#diff-ae89ba240692c2742cc545fd2f57ae82d78e9fce03e3bedc5cfc1af8acbcc1a0R93
blocks https://github.com/nextcloud/talk-android/pull/3812/files#r1568518960
Fix to check if a conversation is "Note to self" by checking the ConversationType instead to check conversation name by hardcoded string
> fix to set ConversationType for "Note to self"

- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
fix to show "Note to self" icon in conversation info
followup to https://github.com/nextcloud/talk-android/pull/3842
> fix to show "Note to self" icon in conversation info

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
I couldn't reproduce the bug that caused the condition to be implemented, but I do faintly recall that `totalItemCount` and `page` were the same when the bug occurred, so I kept this new conditional in place to play it safe.
> Fix onLoadMore not refreshing instantly

- app/src/main/java/com/nextcloud/talk/callnotification/CallNotificationActivity.kt
Before this fix, KEY_CALL_VOICE_ONLY was not included in the intent extras so call always started as videocall
followup fix to https://github.com/nextcloud/talk-android/pull/3830
> fix to open calls as voice only when user clicked on voice button

- LICENSES/LicenseRef-NextcloudTrademarks.txt
- app/src/main/res/drawable/ic_launcher_foreground.xml
- app/src/main/res/drawable/ic_logo.xml
- app/src/main/res/drawable/ic_talk.xml
- app/src/qa/res/drawable/ic_launcher_foreground.xml
> fix: Have correct SPDX license header for logo/trademarked items

- app/src/main/java/com/nextcloud/talk/account/AccountVerificationActivity.kt
- app/src/main/java/com/nextcloud/talk/account/ServerSelectionActivity.kt
- app/src/main/java/com/nextcloud/talk/account/SwitchAccountActivity.kt
- app/src/main/java/com/nextcloud/talk/account/WebViewLoginActivity.kt
- app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
especially for branded clients the primary color might not look good.
---|---
---|---
> set light or dark bar colors for login screens instead primary color

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/openconversations/adapters/OpenConversationsAdapter.kt
- app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversation.kt
- app/src/main/java/com/nextcloud/talk/openconversations/data/OpenConversationsRepositoryImpl.kt
- app/src/main/res/layout/activity_open_conversations.xml
- app/src/main/res/layout/rv_item_open_conversation.xml
- app/src/main/res/values/dimens.xml
Resolves #3892
###
🖼️ Screenshots
--|---
> Show description in open conversation list

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
fix #3903
- receive multiple messages when not being in the conversation (or mark some message as unread yourself)
- open the conversation
chat is scrolled down to the latest message
chat is scrolled to the first unread message
> fix unread message behavior

- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
- app/src/main/res/drawable/ic_notification.xml
ic_notification.xml was not existing/not used in android talk app, but on brander there is code to replace ic_notification.xml with a custom icon.
ic_notification.xml is now created with the same icon as for ic_logo.xml and used for notifications. So from now on branded versions have the ability to overwrite the icon.
> use notification logo from separate xml file

- app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
- app/src/main/java/com/nextcloud/talk/diagnose/DiagnoseActivity.kt
- app/src/main/java/com/nextcloud/talk/invitation/InvitationsActivity.kt
- app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
- app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/shareditems/activities/SharedItemsActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/UriUtils.kt
Followup improvements to #3922
With this change, all links that target files in the same nextcloud instance will be opened in the files app, no matter on which screen the link was (e.g. useful when links are posted in conversation descriptions...).
- this solves https://github.com/nextcloud/talk-android/issues/847 at least for links inside the app itself
- share some files url to chat & open
- share some talk url to chat & open
> open internal links for files app from any screen + open talk links inside the app

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- fixes #3935 
Made `mediaPlayerHandler` null safe
> Fixed MediaPlayerHandler crashing on lifecycle change

- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- fixes #3937 
Handle conversation is called when capabilities are retrieved, which can occur before `databaseStorageModule` is created. The fix was to call `initObservers` after the module was created.
> Fixed Database module initialization error

- app/src/main/java/com/nextcloud/talk/ui/MessageInput.kt
followup to https://github.com/nextcloud/talk-android/pull/3970
When opening the chat the app crashed with
2024-06-18 10:59:45.039 30757-30757 AndroidRuntime          com.nextcloud.talk2                  E  FATAL EXCEPTION: main
Process: com.nextcloud.talk2, PID: 30757
java.lang.StackOverflowError: stack size 8192KB
at com.nextcloud.talk.ui.MessageInput.getMessageSendButton(MessageInput.kt:75)
Hint in AS was:
Now field from base class com.stfalcon.chatkit.messages.MessageInput shadows the property with custom getter from derived class com.nextcloud.talk.ui.MessageInput. This behavior will be changed soon in favor of the property. Please use explicit cast to com.stfalcon.chatkit.messages.MessageInput if you wish to preserve current behavior. See …
> Avoid StackOverflowError when opening chat (kotlin2.0 fix)

- .github/workflows/qa.yml
https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/
N/A
> build(qa): Switch deprecated `set-output` to `$GITHUB_OUTPUT`

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/chat/data/ChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/NetworkChatRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
- app/src/main/java/com/nextcloud/talk/models/json/participants/TalkBan.kt
- app/src/main/java/com/nextcloud/talk/models/json/participants/TalkBanOCS.kt
- app/src/main/java/com/nextcloud/talk/models/json/participants/TalkBanOverall.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/DialogBanListFragment.kt
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
- app/src/main/res/drawable/baseline_block_24.xml
- app/src/main/res/layout/activity_conversation_info.xml
- app/src/main/res/layout/ban_item_list.xml
- app/src/main/res/layout/dialog_ban_actor.xml
- app/src/main/res/layout/fragment_dialog_ban_list.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/strings.xml
> 🚫 Allow Banning Users and Guests

- app/build.gradle
> bump version to 20.1.0 Alpha 01

- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
Resolves https://github.com/nextcloud/talk-android/issues/4108
Allow editing of "Note to self" messages forever
> No Edit Time limit on Note to Self Messages

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
This will fix to scroll to the last read message when a chat is opened.
See comment https://github.com/nextcloud/talk-android/pull/4069#pullrequestreview-2277339509
Some refactorings were made that are not necessary for the fix (I tried to also show the "Unread messages" hint in the adapter but came to the conclusion this is not a good idea until chatkit is removed. Chatkit doesn't support to add some item in between but only at the end or start which will make it too complicated..)
> fix to scroll to last read message

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
- app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
- app/src/main/java/com/nextcloud/talk/data/database/dao/ConversationsDao.kt
> Bug fixes for offline support

- app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
fix https://github.com/nextcloud/talk-android/issues/4134
new PR because of github merge error in https://github.com/nextcloud/talk-android/pull/4163
> fix NPE when baseUrl is missing

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
In dark mode, the call buttons looked like disabled otherwise.
There is still the 3-dots menu next to the call icons which looks like disabled for dark and light mode. But this is a different bug that needs to be fixed in another branch(could not find the reason for now).
fix #4012
---|---
> remove theming of call buttons to remove disabled look for dark mode

- app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
otherwise it's an endless loop without delay which may stress the devices...
> sleep one second before websocket reconnect

- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
- app/src/main/res/values/strings.xml
> Queuing offline messages to be sent online

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/adapters/ParticipantDisplayItem.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/models/ExternalSignalingServer.kt
- app/src/main/java/com/nextcloud/talk/models/json/signaling/settings/FederationHelloAuthParams.kt
- app/src/main/java/com/nextcloud/talk/models/json/signaling/settings/FederationSettings.kt
- app/src/main/java/com/nextcloud/talk/models/json/websocket/RoomFederationWebSocketMessage.kt
- app/src/main/java/com/nextcloud/talk/models/json/websocket/RoomWebSocketMessage.kt
- app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
- app/src/main/java/com/nextcloud/talk/webrtc/WebSocketConnectionHelper.java
- app/src/main/java/com/nextcloud/talk/webrtc/WebSocketInstance.kt
- app/src/test/java/com/nextcloud/talk/call/CallParticipantListExternalSignalingTest.java
- app/src/test/java/com/nextcloud/talk/call/CallParticipantListInternalSignalingTest.java
- app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverParticipantListTest.java
This pull request adds support for federated calls when using the external signaling server (note that support for the external signaling server in a federated conversation was not added to the chat view, though, only to the call view for now).
To do that now the federation properties from the signaling settings are given to the external signaling server when joining a room (as described in https://github.com/nextcloud/spreed/pull/12604), and the avatar of participants in call view now take into account the `actorType` and `actorId` fields in the `participants->update` signaling message to get a federated avatar if needed (as described in https://github.com/nextcloud/spreed/pull/12863).
Both changes should be backwards compatible with older Talk versions; if an older Talk version is used …
> Add support for federated calls

- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
otherwise it showed "connection gained" with red background when loosing connection for the first time
> fix to show connection lost hint when internet is gone

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/models/json/conversations/Conversation.kt
With server version 23.0.12 it happened that the chat did not load because values were null. Now default values in json model are set
> fix to load chat for old server version

- app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
if invitations were not supported (or failed for some reason), the account did not show up.
This was one scenario how it could happen that accounts did not show up in account switcher dialog. fix #2446
> fix to show accounts from older servers in switch account dialog

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
fix #4238
The messageInputFragment was hidden by checkShowMessageInputView(), but it was immediately shown again by checkLobbyState()
This fix will execute checkShowMessageInputView() inside checkLobbyState() in the correct order.
Additionally, the check
checkLobbyState()
has to be already executed in
GetCapabilitiesInitialLoadState
as well as
checkShowCallButtons()
Otherwise the expected behavior would only be set after 30 seconds.
An improvemnt for the future must be to improve the capabilities handling.
> fix to hide messageInputFragment when user has no restriction to write

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
After 30 seconds (when the capabilities were updated) the call buttons of federated conversations were sometimes removed (the logic was added back then when fed calls were not implemented).
However this happened not always because of the check `if (this::spreedCapabilities.isInitialized) {....` 
It seems this check sometimes is false when it's supposed to be true. This has be to further investigated and has to be be simplified/improved by a cleaner architecture.
> fix to not remove call buttons for federated conversations after 30 seconds

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
Resolves #4249 
This PR implements:
1. Hide Delete button in the new conversation screen and show it only when conversation avatar is set.
2. Single line textfield for conversation name.
3. Make conversation avatar sustain configuration changes.
> Conversation creation modification

- detekt.yml
Resolve #4014
solve codacy lint warning for composables.
The static code analysis gives a warning when composable functions name start with a capital letter. The functionPattern should be modified to write a composable function name with a capital letter.
> Fix Codacy Warnings -  Ensure Composable Function Names Start with a Capital Letter

- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
- app/src/main/res/drawable/baseline_lock_open_24.xml
- app/src/main/res/values/strings.xml
> Password improvement

- REUSE.toml
- app/src/test/java/com/nextcloud/talk/json/ConversationConversionTest.kt
followup to https://github.com/nextcloud/talk-android/pull/4277
> add copyright header to fix reuse

- app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimePickerFragment.kt
fix #4248
https://github.com/user-attachments/assets/ead05132-3303-4dfb-b0bf-266dd7e510ec
https://github.com/user-attachments/assets/a5a49119-ee9a-4035-961f-13b3fb4d4b79
> [Bug Fix] Fix wrong value when choosing custom reminder date

- app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
> make predefined status use custom time

- app/build.gradle
> Lock kotlin java version

- app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt
> Adjust cacheDir based on Android version

- app/src/main/java/com/nextcloud/talk/call/CallParticipant.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantListNotifier.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/call/MutableCallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/signaling/LocalParticipantMessageNotifier.java
- app/src/main/java/com/nextcloud/talk/signaling/OfferMessageNotifier.java
- app/src/main/java/com/nextcloud/talk/signaling/ParticipantListMessageNotifier.java
- app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
- app/src/main/java/com/nextcloud/talk/webrtc/DataChannelMessageNotifier.java
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionNotifier.java
Given that there is no risk in backporting this I suggest doing it to ease other future backports that might touch the Javadocs too.
> Fix ignored blank lines in Javadocs

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
This change was part of another fix, but I have extracted it to its own pull request for better reviewing, as it is related to the Android activity lifecycle and I am a bit worried to be missing something.
`IN_CONVERSATION` was set when the activity was created and `state` in the intent extras has the value `resume`. As far as I know there is no `state` extra set by default in Android intents, it should be explicitly set, but it is not set anywhere in Talk Android code, so that would make it dead code and safe to remove.
Moreover, [it was added when switching between call view and chat during a call was introduced](https://github.com/nextcloud/talk-android/commit/f7d92908716c22a6218da92578e0344a2aae7faf#diff-ecc1f9971f93c8bb9f1c42a1a78335116efa9b32ac8ca0fa44d92403ad637d03R300). At that …
> Remove dead code to set the call state

- app/src/main/java/com/nextcloud/talk/signaling/SignalingMessageReceiver.java
- app/src/test/java/com/nextcloud/talk/signaling/SignalingMessageReceiverParticipantListTest.java
When the message applies to all participants [the property is all in lower case](https://github.com/nextcloud/spreed/blob/956a1ab00ffb25d87c0f5192333c9b66e56a63fe/lib/Signaling/BackendNotifier.php#L402-L406). The comparison is case sensitive, so the message was ignored and the call was not left by the Talk Android app.
That message is sent only when the external signaling is used. If the internal signaling is used the call is left as expected when the call is ended for everyone; in that case the normal `usersInRoom` message is sent with `inCall` set to disconnected for every participant, and the Android app [leaves the call if the local participant is marked as disconnected](https://github.com/nextcloud/talk-android/blob/fdb8692b59aae8563e680c1a593ce73f48e82848/app/src/main/java/com/nextcl …
> Fix handling of end call for everyone with external signaling

- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
> Time setting for lobby

- app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/11.json
- app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/12.json
- app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
https://github.com/nextcloud/talk-android/pull/4333/files was merged with modified 11.json instead to create 12.json.
This PR will revert 11.json to the old state and and 12.json (DB migration is already in place, just the json was missing)
Not sure if it could have been a problem for released alpha versions, but luckily(😄) the alpha build that could have been affected failed because of a translation error.
> Fix DB migration 11 to 12

- app/src/main/java/com/nextcloud/talk/adapters/messages/AdjustableMessageHolderInterface.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingDeckCardViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLinkPreviewMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingLocationMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/TalkMessagesListAdapter.java
- app/src/main/java/com/nextcloud/talk/call/CallParticipantList.java
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/presenters/MentionAutocompletePresenter.java
- app/src/main/java/com/nextcloud/talk/ui/dialog/ChooseAccountDialogFragment.java
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- detekt.yml
---|---
This PR implements the change requested in [issue #3920](https://github.com/nextcloud/talk-android/issues/3920). 
Messages bubbles in "NoteToSelf" chat room use the full available width now. There is no sense in leaving a start margin, since no other participant can add messages to that chat room.
> Make messages in 'Note To Self' chat room take full available screen width

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
> fix crash for unreadMarker

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
> fix NPE in restoreMessageQueue

- app/src/main/java/com/nextcloud/talk/ui/dialog/MoreCallActionsDialog.kt
- app/src/main/res/layout/dialog_more_call_actions.xml
As the number of provided emojis grew (from 10 to 12), there was a bug that only one emoji was shown.
Putting all 12 emojis in one fixed row would have been too close, so it's implemented to scroll them horizontally
🏚️ Before 
🏡 After
[A](https://github.com/user-attachments/assets/6dac5349-cbbb-47d1-b0e8-b1d1ed5468c7)
> fix to provide all call emojis

- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
> fix NPE currentConversation!!.internalId

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
> Migrating Rxjava to coroutines #1

- app/src/main/java/com/nextcloud/talk/api/NcApi.java
- app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/GuestAccessHelper.kt
- app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
- app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepository.kt
- app/src/main/java/com/nextcloud/talk/repositories/conversations/ConversationsRepositoryImpl.kt
- app/src/main/res/values/strings.xml
> Migrate Rxjava to coroutines #2

- app/build.gradle
- app/src/androidTest/java/com/nextcloud/talk/utils/VibrationUtilsTest.kt
- app/src/main/java/com/nextcloud/talk/activities/BaseActivity.kt
- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/activities/CallBaseActivity.java
- app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
- app/src/main/java/com/nextcloud/talk/adapters/items/MentionAutocompleteItem.kt
- app/src/main/java/com/nextcloud/talk/callnotification/CallNotificationActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/io/AudioFocusRequestManager.kt
- app/src/main/java/com/nextcloud/talk/contacts/ContactsActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/extensions/ImageViewExtensions.kt
- app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/NotificationWorker.kt
- app/src/main/java/com/nextcloud/talk/location/GeocodingActivity.kt
- app/src/main/java/com/nextcloud/talk/location/LocationPickerActivity.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/theme/TalkSpecificViewThemeUtils.kt
- app/src/main/java/com/nextcloud/talk/upload/chunked/ChunkedFileUploader.kt
- app/src/main/java/com/nextcloud/talk/utils/DisplayUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/FileUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/ImageEmojiEditText.kt
- app/src/main/java/com/nextcloud/talk/utils/NotificationUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/VibrationUtils.kt
> bump minSdkVersion to 26 and remove old checks

- app/src/main/java/com/nextcloud/talk/conversationinfo/viewmodel/ConversationInfoViewModel.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/SetStatusDialogFragment.kt
> Unable to change user status during a call 

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/DrawableUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/bundle/BundleKeys.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
- app/src/main/res/layout/activity_conversations.xml
- app/src/main/res/layout/activity_settings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
Show a warning whenever something regarding notifications is not set up correctly.
known bug is https://github.com/nextcloud/talk-android/issues/4484 (won't be fixed for now if no one comes up with an idea..)
Warning when notifications are not set up correctly
- On first login, ask directly with popups for notification permission and to ignore battery optimization.
- If this is declined or any other setting is wrong, show a permanent warning. 
- Also: When using mobile device management MDM, it may happen that some permissions are not set up while preparing the phones and users won't see any dialogs on first use. With this change, they now see the permanent warning and are guided what changes need to be made.
- When clicking on the warning, settings are opened and things that need to be …
> Add permanent warning when notifications are not set up correctly

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingVoiceMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/VoiceMessageInterface.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
- app/src/main/java/com/nextcloud/talk/ui/PlaybackSpeedControl.kt
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferences.java
- app/src/main/java/com/nextcloud/talk/utils/preferences/AppPreferencesImpl.kt
- app/src/main/res/layout/fragment_message_input_voice_recording.xml
- app/src/main/res/layout/item_custom_incoming_voice_message.xml
- app/src/main/res/layout/item_custom_outcoming_voice_message.xml
- app/src/main/res/values/strings.xml
- app/src/test/java/com/nextcloud/talk/utils/ParticipantPermissionsTest.kt
This is an implementation of the feature request in issue 3786: 
"Allow voice messages to be played at different speeds"
This PR should not be considered final. There are a few questions to be answered first, I cannot do that myself, however. I need someone from inside the project for that. So this is more a "request for comment" than a PR ;-)
The current implementation does not at all offer a fancy design. The UI is as simplistic as possible. 
I could very well imagine a button that extends when clicked and offers the options in parallel instead of cycling through the offered options as it is currently implemented. But that certainly is something a design expert has to decide. 
The current implementation has 4 speeds it offers (opposed to WhatsApp offering 3): 0.8x, 1.0x, 1.5x, 2.0x. I …
> Add playback speed control to voice messages

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/res/layout/activity_chat.xml
- app/src/main/res/layout/no_saved_messages_view.xml
- app/src/main/res/values/strings.xml
> User now knows if no offline messages are saved when entering a conversation

- CHANGELOG.md
> add changelog entries

- app/build.gradle
- build.gradle
This PR removes unused hilt dependency. 
Renovate failed to update the Hilt dependency due to a conflict between Hilt and KSP plugins  https://github.com/nextcloud/talk-android/pull/4019 . The Hilt plugin is applied in the root project, while KSP is applied in a sub-project, which causes compatibility issues. To avoid complexity, the unused hilt plugin has been removed.
> remove hilt dependency

- app/src/main/java/com/nextcloud/talk/openconversations/ListOpenConversationsActivity.kt
- app/src/main/res/layout/activity_open_conversations.xml
- app/src/main/res/values/strings.xml
> Add clear icon for search view in open conversations

- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
> Set remainder for messages in federated conversation

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
> fix(ktlint): correct code formatting

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
- app/src/test/java/android/util/Log.java
- app/src/test/java/com/nextcloud/talk/webrtc/PeerConnectionWrapperTest.kt
Follow up to #3670
This was part of an upcoming pull request but was extracted for easier reviewing. It adjusts some data channel related code that is either needed for the other pull request (queuing messages if the data channel was not open yet), was incorrect (not disposing of all data channels, sending messages on data channels other than _status_) or could be improved (missing logs, documentation and tests). Please refer to the individual commit messages for details.
As data channels involve several threads (the events are received in the so called WebRTC signaling thread (unrelated to the thread were signaling messages are received), but the PeerConnectionWrapper can be used from RxJava executors, the main thread, the WebRTC signaling thread itself...) synchronization was needed in …
> Improve handling of data channels

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
Fixes a regression introduced in #4527 (specifically, [in the refactoring of the creation of `PeerConnectionWrapper` objects in _CallActivity.kt_](https://github.com/nextcloud/talk-android/commit/12620a5c3eaed9c1dfb0ff9d5b3fbef95df3746d#diff-4c6a4b66806639eeb2704fc66676d5369afb70e0ef78b5fc84be268638f7e900L2335-R2388)
The SDP constraints for publisher connections when the MCU is used were set for all connections. Those constraints set `OfferToReceiveAudio` and `OfferToReceiveVideo` to false, which disables receiving audio and video when the local participant is the one sending the offer. Therefore, audio and video was not received when the MCU was not used and the local participant was the one initiating the connection (which is based on the session IDs of both the local and remote …
> Fix audio and video not received

- .github/workflows/unit-tests.yml
See https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle
and
https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated
> Migrate Gradle action

- app/src/main/java/com/nextcloud/talk/utils/FileViewerUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/Mimetype.kt
Resolve #4537
webm videos can be played with the internal player for Android 8.0 and above and it was added to the supported formats.
> open .webm video files with internal player

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/call/LocalCallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/call/LocalCallParticipantModelNotifier.java
- app/src/main/java/com/nextcloud/talk/call/LocalStateBroadcaster.java
- app/src/main/java/com/nextcloud/talk/call/LocalStateBroadcasterMcu.java
- app/src/main/java/com/nextcloud/talk/call/LocalStateBroadcasterNoMcu.java
- app/src/main/java/com/nextcloud/talk/call/MessageSender.java
- app/src/main/java/com/nextcloud/talk/call/MessageSenderMcu.java
- app/src/main/java/com/nextcloud/talk/call/MessageSenderNoMcu.java
- app/src/main/java/com/nextcloud/talk/call/MutableLocalCallParticipantModel.java
- app/src/main/java/com/nextcloud/talk/webrtc/PeerConnectionWrapper.java
- app/src/test/java/com/nextcloud/talk/call/LocalCallParticipantModelTest.kt
- app/src/test/java/com/nextcloud/talk/call/LocalStateBroadcasterMcuTest.kt
- app/src/test/java/com/nextcloud/talk/call/LocalStateBroadcasterNoMcuTest.kt
- app/src/test/java/com/nextcloud/talk/call/LocalStateBroadcasterTest.kt
- app/src/test/java/com/nextcloud/talk/call/MessageSenderMcuTest.kt
- app/src/test/java/com/nextcloud/talk/call/MessageSenderNoMcuTest.kt
- app/src/test/java/com/nextcloud/talk/call/MessageSenderTest.kt
Fixes #3358
Requires #4536
First of all, sorry for the long, long delay and thanks a lot to everyone who provided information on the issue.
Note that the description below treats #4536 as part of this pull request (so the behaviours of the code are described in a pre-4536 state).
The problem started to happen in https://github.com/nextcloud/talk-android/commit/a0fa84124b9959a6b47a8021c3c57467461cc8dc because, as described in the first part of https://github.com/nextcloud/talk-android/issues/3358#issuecomment-2254251856, the video is set as not available (or, rather, not known if available) when the connection state changes to `NEW` or `CHECKING`. This was done following the implementation of the WebUI; the idea is that until the connection is completly established it is not really known …
> Fix sending local state to other participants

- app/src/main/res/values-v28/arrays.xml
- app/src/main/res/values/arrays.xml
- app/src/main/res/values/strings.xml
> Added option `Immediate` for passcode timeout.

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
fix #4610
It seems there could have been a race condition because currentUser was initialized too late.
I was not able to reproduce but hopefully this fixes it:
- initialize currentUser earlier (moved from onResume to onCreate)
- use currentUserProvider instead userManager
NPEs were reported via gplay:
1)
```
Exception java.lang.NullPointerException:
at com.nextcloud.talk.conversationlist.ConversationsListActivity.addToConversationItems (ConversationsListActivity.kt:851)
at com.nextcloud.talk.conversationlist.ConversationsListActivity.access$addToConversationItems (ConversationsListActivity.kt:151)
at com.nextcloud.talk.conversationlist.ConversationsListActivity$initObservers$5$1.invokeSuspend (ConversationsListActivity.kt:394)
at …
```
> hopefully fix NPE for currentUser in addToConversationItems

- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
- app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitor.kt
- app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitorImpl.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt
fix #4503
By using
`networkMonitor.isOnline.first()`
the function
`unregisterNetworkCallback`
was triggered, which sometimes caused the ConnectivityManager$TooManyRequestsException.
So each time isOnline.first() was called, the callbackFlow would:
- Register a new NetworkCallback.
- Emit a value and cancel the flow.
- Unregister the NetworkCallback.
The exception was:
```
Exception android.net.ConnectivityManager$TooManyRequestsException:
at android.net.ConnectivityManager.convertServiceException (ConnectivityManager.java:3771)
at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:3960)
at android.net.ConnectivityManager.sendRequestForNetwork (ConnectivityManager.java:3967)
at android.net.ConnectivityManager.registerNetworkCallback …
```
> fix TooManyRequestsException

- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/data/network/OfflineFirstConversationsRepository.kt
- app/src/main/java/com/nextcloud/talk/dagger/modules/RepositoryModule.kt
- app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitor.kt
- app/src/main/java/com/nextcloud/talk/data/network/NetworkMonitorImpl.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
manual backport of https://github.com/nextcloud/talk-android/pull/4611
> manual backport of PR #4598 (TooManyRequestsException)

- app/src/main/res/values/setup.xml
resolve #3907
resolve #4421
This will enable the "Select authentication certificate" option on server selection screen.
I plan to have this enabled for v21.0.0 RC1 and collect some feedback before deciding to include it in v21.0.0 final.
> enable to select authentication cert in server selection screen

- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
> Rework can leave/delete conversation

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
fix #4628
If chatMessageList is empty after handleSystemMessages it makes no sense to call the following methods. Also processMessagesFromTheFuture was executed which caused that the popup was shown.
A better solution for the future should be to handle(remove) the "to-hide" system messages already in the repo or viewmodel
> no "unread messages" popup for invisible messages

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
> fix shimmer and "offlineNoMessages"-info handling

- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/ConversationsListBottomDialog.kt
- app/src/main/res/layout/activity_conversation_info.xml
- app/src/main/res/layout/activity_conversations.xml
- app/src/main/res/layout/dialog_conversation_operations.xml
- app/src/main/res/values/strings.xml
> Follow up fixes for 'Archive Conversations

- app/src/main/java/com/nextcloud/talk/utils/ChatMessageUtils.kt
> Message of type actorId "sample" should show talk logo avatar

- app/src/main/java/com/nextcloud/talk/ui/dialog/DateTimeCompose.kt
From Talk-Helpdesk, aligns with material standards
---|---
> Switched the "Close" and "Set" Buttons in the remind-me-later dialog

- app/src/main/java/com/nextcloud/talk/data/user/UsersRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/users/UserManager.kt
resolve #4492 (commits 307ebd384d7893743397ec3736e11f36693c3bfc and 22b8b59fb318183b53ffc13e528b0fc052113ef9 might not fix the root cause but commit b69f21580a70442b474da02252fa0278e0f7cd5b makes sure DB state is healed)
there will be more followup PR's regarding multi user issues...
> Bugfix/4492/fix missing users in UI

- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationActivity.kt
- app/src/main/java/com/nextcloud/talk/conversationcreation/ConversationCreationViewModel.kt
- app/src/main/java/com/nextcloud/talk/conversationinfoedit/ConversationInfoEditActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/CapabilitiesUtil.kt
- app/src/main/res/layout/activity_conversation_info_edit.xml
> Set limit on conversation description length

- .idea/inspectionProfiles/ktlint.xml
- app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
- app/src/main/java/com/nextcloud/talk/adapters/items/FlexibleItemViewType.kt
- app/src/main/java/com/nextcloud/talk/contacts/ContactsRepository.kt
- app/src/main/java/com/nextcloud/talk/contacts/ContactsRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/contacts/ContactsViewModel.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/test/java/com/nextcloud/talk/contacts/repository/FakeRepositoryError.kt
- app/src/test/java/com/nextcloud/talk/contacts/repository/FakeRepositorySuccess.kt
- fixes #4453 
- fixes #4657 
Maybe use the sectional feature of the flexible adapter to organize this.
> Fixing and improving main search

- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
fix https://github.com/nextcloud/talk-android/issues/4707
> No longer does edit button overlap the recordAudioButton

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
onDestroy is not called when navigating to the next activity or bringing the app to background. That's why the adapter was not set to null and all messages were added another time the next time the activity comes to foreground. With this fix, the adapter is set to null in onStop.
This also perfectly explains issue #4673 so i will close it with this PR... 
fix #4673
1. open chat (best is one with only a few messages to see immediately when something is duplicated)
2. navigate to ConversationInfo screen or press home button
3. come back to chat with return or bring app back to foreground
- messages are duplicated
messages are not dupliacted
> Avoid duplicated messages when activity comes back from background

- app/src/main/java/com/nextcloud/talk/adapters/messages/SystemMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/models/json/chat/ChatUtils.kt
Resolve #4672
Clicking on the testing android2 should redirect to a website.
> Make link clickable

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
> init other data earlier than ConversationModel

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
A NPE was reported for ConversationsListActivity.kt:537
Adapter is accessed with !! while it is not safe to access in term of lifecycle. So there could have been a race condition.
The overall problem is not solved and may even have to wait for migration to Compose. This is just a quickfix for v21.0.0
Reported crash was :
```
Exception java.lang.NullPointerException:
at com.nextcloud.talk.conversationlist.ConversationsListActivity.filterConversation (ConversationsListActivity.kt:537)
at com.nextcloud.talk.conversationlist.ConversationsListActivity.setConversationList (ConversationsListActivity.kt:472)
at com.nextcloud.talk.conversationlist.ConversationsListActivity.access$setConversationList (ConversationsListActivity.kt:158)
at com.nextcloud.talk.conversationlist.ConversationsListActivity$ …
```
> avoid Npe for adapter in ConversationsListActivity

- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/res/layout/item_custom_incoming_text_message.xml
- app/src/main/res/layout/item_custom_outcoming_text_message.xml
> Edit bot messages in 1:1 conversations

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/res/layout/activity_conversations.xml
- app/src/main/res/values/strings.xml
Resolve https://github.com/nextcloud/talk-android/issues/2737 (and replace https://github.com/nextcloud/talk-android/pull/4760)
Since offline support it makes more sense to view this as a permanent warning on top, which still allows to see all offline saved conversations. The actions are still available via account switcher.
before | after
------- | --------
> show maintenance warning in conv list on top

- app/src/main/res/layout/activity_settings.xml
> move notification warning setting to bottom of category

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
- app/src/main/java/com/nextcloud/talk/jobs/UploadAndShareFilesWorker.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/AttachmentDialog.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/FileAttachmentPreviewFragment.kt
- app/src/main/res/drawable/baseline_photo_library_24.xml
- app/src/main/res/layout/dialog_attachment.xml
- app/src/main/res/values/strings.xml
resolve #4313
- Add [Photo picker](https://developer.android.com/training/data-storage/shared/photopicker#kotlin)  to have access to photos and videos with a single click without having to grant file permissions.
- Open the photo picker also with a longclick on the attachment icon.
This PR also replaces https://github.com/nextcloud/talk-android/issues/4715 (photo picker is now used instead because it's more privacy friendly)
Please test all kind of different scenarios to add photos/files to the chat and be aware if permissions behave like expected. (File permissions are only necessary when selecting "Upload from device")
Sidenote: There is currently a bug that files are shown duplicated after uploading (https://github.com/nextcloud/talk-android/issues/4764 should be related). This has to …
> Add new photo picker

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
- app/src/main/res/layout/item_custom_incoming_text_message.xml
- app/src/main/res/layout/item_custom_outcoming_text_message.xml
- app/src/main/res/values/strings.xml
> Edit checkbox messages directly

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/res/layout/call_activity.xml
- app/src/main/res/values/dimens.xml
This PR will switch video capture for calls between 4:3 and 16:9 ratio depending on portrait/ landscape mode. This results in a higher Field of View.
Before this change, 16:9 was always applied to the video capture. Now 4:3 is applied for portrait and 19:9 for landscape.
Also: simplify placement of self video view (it was buggy) as well as applying the ratio there as well.
🏚️ Before: Smartphone held in portrait mode (16:9) | 🏡 After: Smartphone held in portrait mode (4:3) 
---|---
> switch video capture between 4:3 and 16:9 ratio for portrait/landscape

- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
fix #4764
fix https://github.com/nextcloud/talk-android/issues/4690
this replaces https://github.com/nextcloud/talk-android/pull/4801
(also see https://github.com/nextcloud/talk-android/pull/4688 for a similar fix where the scope handling was introduced)
> fix duplicate messages because of multiple scopes

- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
as chatDao.getTempMessageForConversation could have returned null
> Avoid Npe in sendChatMessage

- app/src/main/java/com/nextcloud/talk/contacts/ContactsRepositoryImpl.kt
- app/src/main/java/com/nextcloud/talk/data/user/model/User.kt
There were crash reports for:
```
Exception java.lang.RuntimeException:
...
Caused by com.nextcloud.talk.utils.NoSupportedApiException: at com.nextcloud.talk.utils.ApiUtils.getConversationApiVersion (ApiUtils.kt:134) at com.nextcloud.talk.contacts.ContactsRepositoryImpl.<init> (ContactsRepositoryImpl.kt:28)
```
This could happen because of missing capabilities for user and should be fixed. As a fallback, API v4 is guessed
> add hotfix to avoid NoSupportedApiException in ContactsRepositoryImpl

- .idea/inspectionProfiles/ktlint.xml
- app/src/main/java/com/nextcloud/talk/api/NcApiCoroutines.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/ChatNetworkDataSource.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/RetrofitChatNetwork.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/ChatViewModel.kt
- app/src/main/java/com/nextcloud/talk/contacts/ImageRequest.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/jobs/AccountRemovalWorker.java
- app/src/main/java/com/nextcloud/talk/jobs/CapabilitiesWorker.java
- app/src/main/java/com/nextcloud/talk/ui/ComposeChatAdapter.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/ContextChatCompose.kt
- app/src/main/java/com/nextcloud/talk/utils/ApiUtils.kt
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
- app/src/main/res/layout/activity_conversations.xml
- fixes #4433 
https://github.com/user-attachments/assets/e0586514-9811-4a5e-91a3-8404220498e8
> Improving search for chat messages

- app/src/main/java/com/nextcloud/talk/application/NextcloudTalkApplication.kt
`SSLSocketFactoryCompat` relies on `SSLContext.getInstance("TLS")`, which is called from `componentApplication.inject(this)` in `NextcloudTalkApplication.onCreate()` - before Conscrypt is set as the provider.
This caused issues on Android 7.0 devices when connecting to Nextcloud's push notification server. The result was a handshake error, because Android 7.0's native implementation only supports TLSv1.2 and the secp256r1 group, while the server supports only secp384r1.
Setting Conscrypt as a provider earlier ensures that the native implementation is not used, and the connection completes successfully.
Call stack:
```
<init>:44, SSLSocketFactoryCompat (com.nextcloud.talk.utils.ssl)
provideSslSocketFactoryCompat:156, RestModule (com.nextcloud.talk.dagger.modules) …
```
> fix Conscrypt initialization order

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/webrtc/WebRtcAudioManager.java
fix https://github.com/nextcloud/talk-android/issues/4920
add a new 'default' audio device option in audio manager (not in ui). this stops auto-switch to bluetooth being disabled by 'user selected audio device' being set in code and not by user.
if the user actively selects an audio option a new bluetooth connection will not automatically switch away from that selection.
nothing
no new tests required.
backporting not required.
> automatic switch to and away from bluetooth audio if no audio actively selected by user

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/res/layout/call_activity.xml
show own video in PIP mode for group calls
fix "See PIP overlay doesn't show any video peer, only a thumbnail" from https://github.com/nextcloud/talk-android/issues/4916
> Improve pip mode

- app/src/main/java/com/nextcloud/talk/ui/dialog/MessageActionsDialog.kt
- app/src/main/res/layout/dialog_message_actions.xml
- app/src/main/res/values/strings.xml
Resolve #4906 #4908
- recently used emojis will be displayed on long press of a message.
- Reaction list should be shared between reacting on messages and user status.
> Use recent emojis in message actions dialog + use same recent emojis like for status picker

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
- app/src/main/res/drawable/baseline_article_24.xml
- app/src/main/res/drawable/baseline_audiotrack_24.xml
- app/src/main/res/drawable/baseline_bar_chart_24.xml
- app/src/main/res/drawable/baseline_contacts_24.xml
- app/src/main/res/drawable/baseline_image_24.xml
- app/src/main/res/drawable/baseline_insert_drive_file_24.xml
- app/src/main/res/drawable/baseline_location_pin_24.xml
- app/src/main/res/drawable/baseline_mic_24.xml
- app/src/main/res/drawable/baseline_video_24.xml
- app/src/main/res/values/strings.xml
> Improve subline when last message is attachment 

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
> Fixing bugs with Conversation search

- app/build.gradle
- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/java/com/nextcloud/talk/utils/message/MessageUtils.kt
> 🧮 Markdown Tables

- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
Hide archive conversations from the conversation list in default view.
> hide archive conversations from conversation list in default view

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
- app/src/main/java/com/nextcloud/talk/call/components/ParticipantGrid.kt
followup to #4947
This will remove the workaround regarding heightForNonGridComponents by using a BoxWithConstraints
---|---
B | A
> simplify call grid design logic for voice only calls

- app/src/main/java/com/nextcloud/talk/activities/CallActivity.kt
There was a report that the app crashed after coming back from PIP mode.
And i once saw in logs
`call to OpenGL ES API with no current context (logged once per thread)`
By initializing rootEglBase very early there is a chance this fixes these issues.
**Might** fix https://github.com/nextcloud/talk-android/issues/4982
---|---
B | A
> initialize rootEglBase earlier (hopefully fixes crash)

- app/src/main/java/com/nextcloud/talk/adapters/messages/IncomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
> Fixes message timestamp color

- app/src/main/java/com/nextcloud/talk/chat/ChatActivity.kt
- app/src/main/res/layout/remainder_to_delete_conversation.xml
- app/src/main/res/values/strings.xml
manual backport of https://github.com/nextcloud/talk-android/pull/5061
> fix wrong plurals implementation

- .github/workflows/analysis.yml
Trying to fix
https://github.com/nextcloud/android-config/pull/248/files
which caused that analysis is not only blocked for forks, bit also for merge commits.
Solution: If it's not a PR the step should be omitted..
This commit will be checked when workflow runs on github. It will be merged just to test it's working..
> Try to run analysis also for merge commits

- app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/17.json
- app/src/main/java/com/nextcloud/talk/adapters/messages/OutcomingTextMessageViewHolder.kt
- app/src/main/java/com/nextcloud/talk/chat/MessageInputFragment.kt
- app/src/main/java/com/nextcloud/talk/chat/data/ChatMessageRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/data/model/ChatMessage.kt
- app/src/main/java/com/nextcloud/talk/chat/data/network/OfflineFirstChatRepository.kt
- app/src/main/java/com/nextcloud/talk/chat/viewmodels/MessageInputViewModel.kt
- app/src/main/java/com/nextcloud/talk/data/database/dao/ChatMessagesDao.kt
- app/src/main/java/com/nextcloud/talk/data/database/mappers/ChatMessageMapUtils.kt
- app/src/main/java/com/nextcloud/talk/data/database/model/ChatMessageEntity.kt
- app/src/main/java/com/nextcloud/talk/data/database/model/SendStatus.kt
- app/src/main/java/com/nextcloud/talk/data/source/local/Migrations.kt
- app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
- app/src/main/java/com/nextcloud/talk/data/source/local/converters/SendStatusConverter.kt
- app/src/main/java/com/nextcloud/talk/ui/dialog/TempMessageActionsDialog.kt
- app/src/main/java/com/nextcloud/talk/utils/preview/ComposePreviewUtilsDaos.kt
this should fix #4921 (although i was never able to reproduce it)
This adds a sending status to make sure messages that are being sent are not sent again while they are not yet contained in the chat messages list from server.
Will be further improved when solving https://github.com/nextcloud/talk-android/issues/4596
> avoid duplicate messages

- app/src/main/java/com/nextcloud/talk/call/components/ParticipantGrid.kt
- app/src/main/java/com/nextcloud/talk/call/components/ParticipantTile.kt
fix #5073
LazyVerticalGrid was measured with infinite height, which Compose does not allow. By applying the availableHeight explicitly, this should fix the Exception:
```
Exception java.lang.IllegalStateException: Vertically scrollable component was measured with an infinity maximum height constraints, which is disallowed. One of the common reasons is nesting layouts like LazyColumn and Column(Modifier.verticalScroll()). If you want to add a header before the list of items please add a header as a separate item() before the main items() inside the LazyColumn scope. There are could be other reasons for this to happen: your ComposeView was added into a LinearLayout with some weight, you applied Modifier.wrapContentSize(unbounded = true) or wrote a custom layout. Please try to remove the …
```
> fix crash in call view

- app/src/main/java/com/nextcloud/talk/conversationinfo/ConversationInfoActivity.kt
- show delete all messages in one to one conversation only when canDeleteConversation is true
> Show delete all messages in 1:1 only when canDeleteConversation is true

- app/src/main/java/com/nextcloud/talk/adapters/items/ContactItem.kt
- app/src/main/java/com/nextcloud/talk/adapters/items/FlexibleItemViewType.kt
- app/src/main/java/com/nextcloud/talk/conversationlist/ConversationsListActivity.kt
- app/src/main/java/com/nextcloud/talk/messagesearch/MessageSearchActivity.kt
A contact (so not a conversation yet!) had the VIEW_TYPE 2131558677, but 2131558687 was expected to identify the type, see FlexibleViewType.kt
The checks in onItemClick are replaced to directly check the type via kotlin "is" method.
best solution for future: FlexibleAdapter should be removed!-> replace with Compose!
> fix that contact in search is clickable

- app/src/main/java/com/nextcloud/talk/account/BrowserLoginActivity.kt
backport of https://github.com/nextcloud/talk-android/pull/5189
replaces https://github.com/nextcloud/talk-android/pull/5193
> Fixed Login V2 Bug

- app/src/main/java/com/nextcloud/talk/settings/SettingsActivity.kt
> Read status/Typing status setting is misconfigured

- app/build.gradle
- app/schemas/com.nextcloud.talk.data.source.local.TalkDatabase/10.json
- app/src/androidTest/java/com/nextcloud/talk/data/database/migrations/MigrationsTest.kt
- app/src/main/java/com/nextcloud/talk/data/source/local/TalkDatabase.kt
- fixes #5168
Includes explicit tests for all manual migrations, and a implicit test for all migrations from version 10 (last version before offline support).
> Schema 10.json was corrupted, which resulted in test
failing. It was from the offline support days, where the
database was updated, but not the version, which updated
10.json instead of 11.json. Replaced with proper schema
from the 9-10 auto migration.
> Adding Migration Tests

- app/src/main/java/com/nextcloud/talk/adapters/items/ConversationItem.kt
Aftermath of this https://github.com/nextcloud/talk-android/pull/5205
An unexpected side effect was reported: the "Note to Self" image randomly appears for different chats
https://github.com/nextcloud/talk-android/pull/5205#issuecomment-3187866026
Attempting to fix by explicitly removing the image from the viewholder before loading the new one.
> Handles wrong image shown for some conversations

- app/src/main/res/layout/item_thread_title.xml
and title size matching the messages
---|---
B | A
> Make thread icon dark/light aware 
